// CLOSED — failing line amc12b_2020_p13-452: theorem amc12b_2020_p13, Dafny line 452 (ERR: assertion might not hold)
// failing Dafny line: assert ((((Real.sqrt(Real.div(Real.log(3.0), Real.log(2.0))) * Real.sqrt(Real.div(Real.log(3.0), Real.log(2.0)))) + (Real.sqrt(Real.div(Real.log(2.0), Real.log(3.0))) * Real.sqrt(Real.div(Real.log(2.0
// Lean step: have h₃₆₁₆ : 0 < Real.sqrt (Real.log 3 / Real.log 2) * Real.sqrt (Real.log 2 / Real.log 3) := by positivity
// hypotheses: 22 facts Z3 had at the line (goal itself removed: 0; the block's own asserts removed: 1); nothing assumed beyond the facts in scope
// how it closes: own-lemma — nothing: the file's own proof body, hypotheses = facts in scope minus the goal and minus the block's own asserts
// Dafny: finished with 27 verified, 0 errors  (flags: dafny verify --isolate-assertions --resource-limit 1000000 --allow-warnings --cores 1, timeout 30 s)

include "../dafny/amc12b_2020_p13.dfy"
lemma {:induction false} vc_amc12b_2020_p13_L452()
  requires Real.div(Real.log(6.0), Real.log(2.0)) + Real.div(Real.log(6.0), Real.log(3.0)) == Real.div(Real.log(3.0), Real.log(2.0)) + Real.div(Real.log(2.0), Real.log(3.0)) + 2.0
  requires Real.sqrt(Real.div(Real.log(6.0), Real.log(2.0)) + Real.div(Real.log(6.0), Real.log(3.0))) == Real.sqrt(Real.div(Real.log(3.0), Real.log(2.0)) + Real.div(Real.log(2.0), Real.log(3.0)) + 2.0)
  requires Real.div(Real.log(3.0), Real.log(2.0)) > 0.0
  requires Real.div(Real.log(2.0), Real.log(3.0)) > 0.0
  requires Real.div(Real.log(3.0), Real.log(2.0)) * Real.div(Real.log(2.0), Real.log(3.0)) == 1.0
  requires 0.0 < Real.sqrt(Real.div(Real.log(3.0), Real.log(2.0)))
  requires 0.0 < Real.sqrt(Real.div(Real.log(2.0), Real.log(3.0)))
  requires Real.sqrt(Real.div(Real.log(3.0), Real.log(2.0))) * Real.sqrt(Real.div(Real.log(3.0), Real.log(2.0))) == Real.div(Real.log(3.0), Real.log(2.0))
  requires Real.sqrt(Real.div(Real.log(2.0), Real.log(3.0))) * Real.sqrt(Real.div(Real.log(2.0), Real.log(3.0))) == Real.div(Real.log(2.0), Real.log(3.0))
  requires (0.0 <= 1.0 * Real.sqrt(Real.div(Real.log(2.0), Real.log(3.0))) * (1.0 * Real.sqrt(Real.div(Real.log(2.0), Real.log(3.0))))) || (1.0 * Real.sqrt(Real.div(Real.log(2.0), Real.log(3.0))) * (1.0 * Real.sqrt(Real.div(Real.log(2.0), Real.log(3.0)))) < 0.0)
  requires ((0.0 <= 1.0 * Real.sqrt(Real.div(Real.log(2.0), Real.log(3.0))) * (1.0 * Real.sqrt(Real.div(Real.log(2.0), Real.log(3.0))))) && (1.0 * (1.0 * Real.sqrt(Real.div(Real.log(3.0), Real.log(2.0))) * (1.0 * Real.sqrt(Real.div(Real.log(3.0), Real.log(2.0))))) - 1.0 * Real.div(Real.log(3.0), Real.log(2.0)) == 0.0) && (0.0 - 1.0 * Real.sqrt(Real.div(Real.log(2.0), Real.log(3.0))) * (1.0 * Real.sqrt(Real.div(Real.log(2.0), Real.log(3.0)))) * (1.0 * (1.0 * Real.sqrt(Real.div(Real.log(3.0), Real.log(2.0))) * (1.0 * Real.sqrt(Real.div(Real.log(3.0), Real.log(2.0))))) - 1.0 * Real.div(Real.log(3.0), Real.log(2.0))) == 0.0)) || (!(0.0 <= 1.0 * Real.sqrt(Real.div(Real.log(2.0), Real.log(3.0))) * (1.0 * Real.sqrt(Real.div(Real.log(2.0), Real.log(3.0)))) && 1.0 * (1.0 * Real.sqrt(Real.div(Real.log(3.0), Real.log(2.0))) * (1.0 * Real.sqrt(Real.div(Real.log(3.0), Real.log(2.0))))) - 1.0 * Real.div(Real.log(3.0), Real.log(2.0)) == 0.0))
  requires 0.0 <= 1.0 * Real.sqrt(Real.div(Real.log(2.0), Real.log(3.0))) * (1.0 * Real.sqrt(Real.div(Real.log(2.0), Real.log(3.0))))
  requires (0.0 < 1.0 * Real.div(Real.log(3.0), Real.log(2.0))) || (1.0 * Real.div(Real.log(3.0), Real.log(2.0)) <= 0.0)
  requires ((0.0 < 1.0 * Real.div(Real.log(3.0), Real.log(2.0))) && (1.0 * (1.0 * Real.sqrt(Real.div(Real.log(2.0), Real.log(3.0))) * (1.0 * Real.sqrt(Real.div(Real.log(2.0), Real.log(3.0))))) - 1.0 * Real.div(Real.log(2.0), Real.log(3.0)) == 0.0) && (0.0 - 1.0 * Real.div(Real.log(3.0), Real.log(2.0)) * (1.0 * (1.0 * Real.sqrt(Real.div(Real.log(2.0), Real.log(3.0))) * (1.0 * Real.sqrt(Real.div(Real.log(2.0), Real.log(3.0))))) - 1.0 * Real.div(Real.log(2.0), Real.log(3.0))) == 0.0)) || (!(0.0 < 1.0 * Real.div(Real.log(3.0), Real.log(2.0)) && 1.0 * (1.0 * Real.sqrt(Real.div(Real.log(2.0), Real.log(3.0))) * (1.0 * Real.sqrt(Real.div(Real.log(2.0), Real.log(3.0))))) - 1.0 * Real.div(Real.log(2.0), Real.log(3.0)) == 0.0))
  requires (0.0 < 1.0 * Real.sqrt(Real.div(Real.log(3.0), Real.log(2.0))) * (1.0 * Real.sqrt(Real.div(Real.log(2.0), Real.log(3.0))))) || (1.0 * Real.sqrt(Real.div(Real.log(3.0), Real.log(2.0))) * (1.0 * Real.sqrt(Real.div(Real.log(2.0), Real.log(3.0)))) <= 0.0)
  requires ((0.0 < 1.0 * Real.sqrt(Real.div(Real.log(3.0), Real.log(2.0))) * (1.0 * Real.sqrt(Real.div(Real.log(2.0), Real.log(3.0))))) && (1.0 * (1.0 * Real.sqrt(Real.div(Real.log(3.0), Real.log(2.0))) * (1.0 * Real.sqrt(Real.div(Real.log(3.0), Real.log(2.0))))) + 1.0 * (1.0 * Real.sqrt(Real.div(Real.log(2.0), Real.log(3.0))) * (1.0 * Real.sqrt(Real.div(Real.log(2.0), Real.log(3.0))))) + 1.0 * 2.0 - 1.0 * ((1.0 * Real.sqrt(Real.div(Real.log(3.0), Real.log(2.0))) + 1.0 * Real.sqrt(Real.div(Real.log(2.0), Real.log(3.0)))) * (1.0 * Real.sqrt(Real.div(Real.log(3.0), Real.log(2.0))) + 1.0 * Real.sqrt(Real.div(Real.log(2.0), Real.log(3.0))))) < 0.0) && (1.0 * Real.sqrt(Real.div(Real.log(3.0), Real.log(2.0))) * (1.0 * Real.sqrt(Real.div(Real.log(2.0), Real.log(3.0)))) * (1.0 * (1.0 * Real.sqrt(Real.div(Real.log(3.0), Real.log(2.0))) * (1.0 * Real.sqrt(Real.div(Real.log(3.0), Real.log(2.0))))) + 1.0 * (1.0 * Real.sqrt(Real.div(Real.log(2.0), Real.log(3.0))) * (1.0 * Real.sqrt(Real.div(Real.log(2.0), Real.log(3.0))))) + 1.0 * 2.0 - 1.0 * ((1.0 * Real.sqrt(Real.div(Real.log(3.0), Real.log(2.0))) + 1.0 * Real.sqrt(Real.div(Real.log(2.0), Real.log(3.0)))) * (1.0 * Real.sqrt(Real.div(Real.log(3.0), Real.log(2.0))) + 1.0 * Real.sqrt(Real.div(Real.log(2.0), Real.log(3.0)))))) < 0.0)) || (!(0.0 < 1.0 * Real.sqrt(Real.div(Real.log(3.0), Real.log(2.0))) * (1.0 * Real.sqrt(Real.div(Real.log(2.0), Real.log(3.0)))) && 1.0 * (1.0 * Real.sqrt(Real.div(Real.log(3.0), Real.log(2.0))) * (1.0 * Real.sqrt(Real.div(Real.log(3.0), Real.log(2.0))))) + 1.0 * (1.0 * Real.sqrt(Real.div(Real.log(2.0), Real.log(3.0))) * (1.0 * Real.sqrt(Real.div(Real.log(2.0), Real.log(3.0))))) + 1.0 * 2.0 - 1.0 * ((1.0 * Real.sqrt(Real.div(Real.log(3.0), Real.log(2.0))) + 1.0 * Real.sqrt(Real.div(Real.log(2.0), Real.log(3.0)))) * (1.0 * Real.sqrt(Real.div(Real.log(3.0), Real.log(2.0))) + 1.0 * Real.sqrt(Real.div(Real.log(2.0), Real.log(3.0))))) < 0.0))
  requires (0.0 < 1.0 * Real.sqrt(Real.div(Real.log(3.0), Real.log(2.0))) * (1.0 * Real.sqrt(Real.div(Real.log(2.0), Real.log(3.0))))) || (1.0 * Real.sqrt(Real.div(Real.log(3.0), Real.log(2.0))) * (1.0 * Real.sqrt(Real.div(Real.log(2.0), Real.log(3.0)))) <= 0.0)
  requires ((0.0 < 1.0 * Real.sqrt(Real.div(Real.log(3.0), Real.log(2.0))) * (1.0 * Real.sqrt(Real.div(Real.log(2.0), Real.log(3.0))))) && (1.0 * ((1.0 * Real.sqrt(Real.div(Real.log(3.0), Real.log(2.0))) + 1.0 * Real.sqrt(Real.div(Real.log(2.0), Real.log(3.0)))) * (1.0 * Real.sqrt(Real.div(Real.log(3.0), Real.log(2.0))) + 1.0 * Real.sqrt(Real.div(Real.log(2.0), Real.log(3.0))))) - (1.0 * (1.0 * Real.sqrt(Real.div(Real.log(3.0), Real.log(2.0))) * (1.0 * Real.sqrt(Real.div(Real.log(3.0), Real.log(2.0))))) + 1.0 * (1.0 * Real.sqrt(Real.div(Real.log(2.0), Real.log(3.0))) * (1.0 * Real.sqrt(Real.div(Real.log(2.0), Real.log(3.0))))) + 1.0 * 2.0) < 0.0) && (1.0 * Real.sqrt(Real.div(Real.log(3.0), Real.log(2.0))) * (1.0 * Real.sqrt(Real.div(Real.log(2.0), Real.log(3.0)))) * (1.0 * ((1.0 * Real.sqrt(Real.div(Real.log(3.0), Real.log(2.0))) + 1.0 * Real.sqrt(Real.div(Real.log(2.0), Real.log(3.0)))) * (1.0 * Real.sqrt(Real.div(Real.log(3.0), Real.log(2.0))) + 1.0 * Real.sqrt(Real.div(Real.log(2.0), Real.log(3.0))))) - (1.0 * (1.0 * Real.sqrt(Real.div(Real.log(3.0), Real.log(2.0))) * (1.0 * Real.sqrt(Real.div(Real.log(3.0), Real.log(2.0))))) + 1.0 * (1.0 * Real.sqrt(Real.div(Real.log(2.0), Real.log(3.0))) * (1.0 * Real.sqrt(Real.div(Real.log(2.0), Real.log(3.0))))) + 1.0 * 2.0)) < 0.0)) || (!(0.0 < 1.0 * Real.sqrt(Real.div(Real.log(3.0), Real.log(2.0))) * (1.0 * Real.sqrt(Real.div(Real.log(2.0), Real.log(3.0)))) && 1.0 * ((1.0 * Real.sqrt(Real.div(Real.log(3.0), Real.log(2.0))) + 1.0 * Real.sqrt(Real.div(Real.log(2.0), Real.log(3.0)))) * (1.0 * Real.sqrt(Real.div(Real.log(3.0), Real.log(2.0))) + 1.0 * Real.sqrt(Real.div(Real.log(2.0), Real.log(3.0))))) - (1.0 * (1.0 * Real.sqrt(Real.div(Real.log(3.0), Real.log(2.0))) * (1.0 * Real.sqrt(Real.div(Real.log(3.0), Real.log(2.0))))) + 1.0 * (1.0 * Real.sqrt(Real.div(Real.log(2.0), Real.log(3.0))) * (1.0 * Real.sqrt(Real.div(Real.log(2.0), Real.log(3.0))))) + 1.0 * 2.0) < 0.0))
  requires 0.0 - 2.0 * (1.0 * Real.div(Real.log(3.0), Real.log(2.0)) * (1.0 * Real.div(Real.log(2.0), Real.log(3.0))) - 1.0 * 1.0) + (1.0 * ((1.0 * Real.sqrt(Real.div(Real.log(3.0), Real.log(2.0))) + 1.0 * Real.sqrt(Real.div(Real.log(2.0), Real.log(3.0)))) * (1.0 * Real.sqrt(Real.div(Real.log(3.0), Real.log(2.0))) + 1.0 * Real.sqrt(Real.div(Real.log(2.0), Real.log(3.0))))) - (1.0 * (1.0 * Real.sqrt(Real.div(Real.log(3.0), Real.log(2.0))) * (1.0 * Real.sqrt(Real.div(Real.log(3.0), Real.log(2.0))))) + 1.0 * (1.0 * Real.sqrt(Real.div(Real.log(2.0), Real.log(3.0))) * (1.0 * Real.sqrt(Real.div(Real.log(2.0), Real.log(3.0))))) + 1.0 * 2.0)) + (0.0 - 2.0 * (1.0 * Real.sqrt(Real.div(Real.log(2.0), Real.log(3.0))) * (1.0 * Real.sqrt(Real.div(Real.log(2.0), Real.log(3.0)))) * (1.0 * (1.0 * Real.sqrt(Real.div(Real.log(3.0), Real.log(2.0))) * (1.0 * Real.sqrt(Real.div(Real.log(3.0), Real.log(2.0))))) - 1.0 * Real.div(Real.log(3.0), Real.log(2.0))))) + (0.0 - 2.0 * (1.0 * Real.div(Real.log(3.0), Real.log(2.0)) * (1.0 * (1.0 * Real.sqrt(Real.div(Real.log(2.0), Real.log(3.0))) * (1.0 * Real.sqrt(Real.div(Real.log(2.0), Real.log(3.0))))) - 1.0 * Real.div(Real.log(2.0), Real.log(3.0))))) + 1.0 * Real.sqrt(Real.div(Real.log(3.0), Real.log(2.0))) * (1.0 * Real.sqrt(Real.div(Real.log(2.0), Real.log(3.0)))) * (1.0 * ((1.0 * Real.sqrt(Real.div(Real.log(3.0), Real.log(2.0))) + 1.0 * Real.sqrt(Real.div(Real.log(2.0), Real.log(3.0)))) * (1.0 * Real.sqrt(Real.div(Real.log(3.0), Real.log(2.0))) + 1.0 * Real.sqrt(Real.div(Real.log(2.0), Real.log(3.0))))) - (1.0 * (1.0 * Real.sqrt(Real.div(Real.log(3.0), Real.log(2.0))) * (1.0 * Real.sqrt(Real.div(Real.log(3.0), Real.log(2.0))))) + 1.0 * (1.0 * Real.sqrt(Real.div(Real.log(2.0), Real.log(3.0))) * (1.0 * Real.sqrt(Real.div(Real.log(2.0), Real.log(3.0))))) + 1.0 * 2.0)) == 0.0
  requires 2.0 * (1.0 * Real.div(Real.log(3.0), Real.log(2.0)) * (1.0 * Real.div(Real.log(2.0), Real.log(3.0))) - 1.0 * 1.0) + (1.0 * (1.0 * Real.sqrt(Real.div(Real.log(3.0), Real.log(2.0))) * (1.0 * Real.sqrt(Real.div(Real.log(3.0), Real.log(2.0))))) + 1.0 * (1.0 * Real.sqrt(Real.div(Real.log(2.0), Real.log(3.0))) * (1.0 * Real.sqrt(Real.div(Real.log(2.0), Real.log(3.0))))) + 1.0 * 2.0 - 1.0 * ((1.0 * Real.sqrt(Real.div(Real.log(3.0), Real.log(2.0))) + 1.0 * Real.sqrt(Real.div(Real.log(2.0), Real.log(3.0)))) * (1.0 * Real.sqrt(Real.div(Real.log(3.0), Real.log(2.0))) + 1.0 * Real.sqrt(Real.div(Real.log(2.0), Real.log(3.0)))))) + 2.0 * (1.0 * Real.sqrt(Real.div(Real.log(2.0), Real.log(3.0))) * (1.0 * Real.sqrt(Real.div(Real.log(2.0), Real.log(3.0)))) * (1.0 * (1.0 * Real.sqrt(Real.div(Real.log(3.0), Real.log(2.0))) * (1.0 * Real.sqrt(Real.div(Real.log(3.0), Real.log(2.0))))) - 1.0 * Real.div(Real.log(3.0), Real.log(2.0)))) + 2.0 * (1.0 * Real.div(Real.log(3.0), Real.log(2.0)) * (1.0 * (1.0 * Real.sqrt(Real.div(Real.log(2.0), Real.log(3.0))) * (1.0 * Real.sqrt(Real.div(Real.log(2.0), Real.log(3.0))))) - 1.0 * Real.div(Real.log(2.0), Real.log(3.0)))) + 1.0 * Real.sqrt(Real.div(Real.log(3.0), Real.log(2.0))) * (1.0 * Real.sqrt(Real.div(Real.log(2.0), Real.log(3.0)))) * (1.0 * (1.0 * Real.sqrt(Real.div(Real.log(3.0), Real.log(2.0))) * (1.0 * Real.sqrt(Real.div(Real.log(3.0), Real.log(2.0))))) + 1.0 * (1.0 * Real.sqrt(Real.div(Real.log(2.0), Real.log(3.0))) * (1.0 * Real.sqrt(Real.div(Real.log(2.0), Real.log(3.0))))) + 1.0 * 2.0 - 1.0 * ((1.0 * Real.sqrt(Real.div(Real.log(3.0), Real.log(2.0))) + 1.0 * Real.sqrt(Real.div(Real.log(2.0), Real.log(3.0)))) * (1.0 * Real.sqrt(Real.div(Real.log(3.0), Real.log(2.0))) + 1.0 * Real.sqrt(Real.div(Real.log(2.0), Real.log(3.0)))))) == 0.0
  requires (1 as real) == 1.0
  requires (0 as real) == 0.0
  ensures   Real.sqrt(Real.div(Real.log(3.0), Real.log(2.0))) * Real.sqrt(Real.div(Real.log(3.0), Real.log(2.0))) + Real.sqrt(Real.div(Real.log(2.0), Real.log(3.0))) * Real.sqrt(Real.div(Real.log(2.0), Real.log(3.0))) + 2.0 == (Real.sqrt(Real.div(Real.log(3.0), Real.log(2.0))) + Real.sqrt(Real.div(Real.log(2.0), Real.log(3.0)))) * (Real.sqrt(Real.div(Real.log(3.0), Real.log(2.0))) + Real.sqrt(Real.div(Real.log(2.0), Real.log(3.0))))
{
              // have h₃₆₁₆ : 0 < Real.sqrt ( ( Real.log ( 3 ) / Real.log ( 2 ) ) ) * Real.sqrt ( (   [type from Lean state]
              assert (0.0 < (Real.sqrt(Real.div(Real.log(3.0), Real.log(2.0))) * Real.sqrt(Real.div(Real.log(2.0), Real.log(3.0))))) by { // @tac 5777-5787
                // [TACTIC: Positivity]
                // positivity proof: the lemma applications Lean's positivity proof is built from (Lean execution 5777-5787 exec 955)
                if (0.0 < Real.sqrt(Real.div(Real.log(3.0), Real.log(2.0)))) && (0.0 < Real.sqrt(Real.div(Real.log(2.0), Real.log(3.0)))) { cert_piece_6(); }  // cert: mul_pos
                if (0.0 < Real.log(3.0)) && (0.0 < Real.log(2.0)) { cert_piece_7(); }  // cert: div_pos
                if (0.0 < Real.log(2.0)) && (0.0 < Real.log(3.0)) { cert_piece_8(); }  // cert: div_pos
                // UNCITED-APPLIED internal ×6 [exec 955 5777-5787]: applications made inside the tactic's own automation, not stated — Real.sqrt_pos_of_pos ×2, Mathlib.Meta.Positivity.log_pos_of_isNat ×2; machinery/glue: Mathlib.Meta.NormNum.isNat_ofNat ×2 (cited in this block, not counted here: div_pos [Lean recorded ×2], mul_pos [Lean recorded ×1])
                assert (0.0 < (Real.sqrt(Real.div(Real.log(3.0), Real.log(2.0))))) && (0.0 < (Real.sqrt(Real.div(Real.log(2.0), Real.log(3.0)))));  // precondition of MulPos (Lean: mul_pos)
                MulPos(Real.sqrt(Real.div(Real.log(3.0), Real.log(2.0))), Real.sqrt(Real.div(Real.log(2.0), Real.log(3.0))));  // cite: mul_pos [applied by the tactic, not named in it]
                assert (0.0 < (Real.log(3.0))) && (0.0 < (Real.log(2.0)));  // precondition of DivPos (Lean: div_pos)
                DivPos(Real.log(3.0), Real.log(2.0));  // cite: div_pos [applied by the tactic, not named in it]
                assert (0.0 < (Real.log(2.0))) && (0.0 < (Real.log(3.0)));  // precondition of DivPos (Lean: div_pos)
                DivPos(Real.log(2.0), Real.log(3.0));  // cite: div_pos [applied by the tactic, not named in it]
              }
              // [TACTIC: «Nlinarith[_]At___» [ Real.sq_sqrt ( le_of_lt h₃₁ ) , Real.sq_sqrt ( le_of_lt h₃₂ ) , h₃₅ ]]
              // (n)linarith certificate: Lean's product pieces and the identity it closed with (Lean execution 5800-5885 exec 956)
              // UNCITED-APPLIED Linarith.mul_eq: certificate piece `(2 : ℝ) * ((1 : ℝ) * (Real.log (3 : ℝ) / Real.log (2 : ℝ)) * ((1 : ℝ) * (Real.log (2 : ℝ) / Real.log (3 : ℝ))) - (1 : ℝ…` not stated: a numeral multiple of a fact (linear: Dafny's arithmetic scales it natively); Lean's premises: ((((1.0 * Real.div(Real.log(3.0), Real.log(2.0))) * (1.0 * Real.div(Real.log(2.0), Real.log(3.0)))) - (1.0 * 1.0)) == 0.0); (2.0 > 0.0)
              // UNCITED-APPLIED Linarith.mul_eq: certificate piece `(2 : ℝ) * -(-((1 : ℝ) * √(Real.log (2 : ℝ) / Real.log (3 : ℝ))) ^ (2 : ℕ) * ((1 : ℝ) * ((1 : ℝ) * √(Real.log (3 : ℝ) / …` not stated: a numeral multiple of a fact (linear: Dafny's arithmetic scales it natively); Lean's premises: ((((1.0 * Real.sqrt(Real.div(Real.log(2.0), Real.log(3.0)))) * (1.0 * Real.sqrt(Real.div(Real.log(2.0), Real.log(3.0))))) * ((1.0 * ((1.0 * Real.sqrt(Real.div(Real.log(3.0), Real.log(2.0)))) * (1.0 * Real.sqrt(Real.div(Real.log(3.0), Real.log(2.0)))))) - (1.0 * Real.div(Real.log(3.0), Real.log(2.0))))) == 0.0); (2.0 > 0.0)
              if (0.0 <= ((1.0 * Real.sqrt(Real.div(Real.log(2.0), Real.log(3.0)))) * (1.0 * Real.sqrt(Real.div(Real.log(2.0), Real.log(3.0)))))) && (((1.0 * ((1.0 * Real.sqrt(Real.div(Real.log(3.0), Real.log(2.0)))) * (1.0 * Real.sqrt(Real.div(Real.log(3.0), Real.log(2.0)))))) - (1.0 * Real.div(Real.log(3.0), Real.log(2.0)))) == 0.0) { assert (-((((1.0 * Real.sqrt(Real.div(Real.log(2.0), Real.log(3.0)))) * (1.0 * Real.sqrt(Real.div(Real.log(2.0), Real.log(3.0))))) * ((1.0 * ((1.0 * Real.sqrt(Real.div(Real.log(3.0), Real.log(2.0)))) * (1.0 * Real.sqrt(Real.div(Real.log(3.0), Real.log(2.0)))))) - (1.0 * Real.div(Real.log(3.0), Real.log(2.0)))))) == 0.0); }  // cert: Linarith.mul_zero_eq
              SqNonneg((1.0 * Real.sqrt(Real.div(Real.log(2.0), Real.log(3.0))))); assert (0.0 <= ((1.0 * Real.sqrt(Real.div(Real.log(2.0), Real.log(3.0)))) * (1.0 * Real.sqrt(Real.div(Real.log(2.0), Real.log(3.0))))));  // cert: sq_nonneg
              // UNCITED-APPLIED Linarith.mul_eq: certificate piece `(2 : ℝ) * -(-((1 : ℝ) * (Real.log (3 : ℝ) / Real.log (2 : ℝ))) * ((1 : ℝ) * ((1 : ℝ) * √(Real.log (2 : ℝ) / Real.log (3…` not stated: a numeral multiple of a fact (linear: Dafny's arithmetic scales it natively); Lean's premises: (((1.0 * Real.div(Real.log(3.0), Real.log(2.0))) * ((1.0 * ((1.0 * Real.sqrt(Real.div(Real.log(2.0), Real.log(3.0)))) * (1.0 * Real.sqrt(Real.div(Real.log(2.0), Real.log(3.0)))))) - (1.0 * Real.div(Real.log(2.0), Real.log(3.0))))) == 0.0); (2.0 > 0.0)
              if (0.0 < (1.0 * Real.div(Real.log(3.0), Real.log(2.0)))) && (((1.0 * ((1.0 * Real.sqrt(Real.div(Real.log(2.0), Real.log(3.0)))) * (1.0 * Real.sqrt(Real.div(Real.log(2.0), Real.log(3.0)))))) - (1.0 * Real.div(Real.log(2.0), Real.log(3.0)))) == 0.0) { assert (-(((1.0 * Real.div(Real.log(3.0), Real.log(2.0))) * ((1.0 * ((1.0 * Real.sqrt(Real.div(Real.log(2.0), Real.log(3.0)))) * (1.0 * Real.sqrt(Real.div(Real.log(2.0), Real.log(3.0)))))) - (1.0 * Real.div(Real.log(2.0), Real.log(3.0)))))) == 0.0); }  // cert: Linarith.mul_zero_eq
              if (0.0 < ((1.0 * Real.sqrt(Real.div(Real.log(3.0), Real.log(2.0)))) * (1.0 * Real.sqrt(Real.div(Real.log(2.0), Real.log(3.0)))))) && (((((1.0 * ((1.0 * Real.sqrt(Real.div(Real.log(3.0), Real.log(2.0)))) * (1.0 * Real.sqrt(Real.div(Real.log(3.0), Real.log(2.0)))))) + (1.0 * ((1.0 * Real.sqrt(Real.div(Real.log(2.0), Real.log(3.0)))) * (1.0 * Real.sqrt(Real.div(Real.log(2.0), Real.log(3.0))))))) + (1.0 * 2.0)) - (1.0 * (((1.0 * Real.sqrt(Real.div(Real.log(3.0), Real.log(2.0)))) + (1.0 * Real.sqrt(Real.div(Real.log(2.0), Real.log(3.0))))) * ((1.0 * Real.sqrt(Real.div(Real.log(3.0), Real.log(2.0)))) + (1.0 * Real.sqrt(Real.div(Real.log(2.0), Real.log(3.0)))))))) < 0.0) { cert_piece_9(); }  // cert: mul_pos_of_neg_of_neg
              // UNCITED-APPLIED Linarith.mul_eq: certificate piece `(2 : ℝ) * -((1 : ℝ) * (Real.log (3 : ℝ) / Real.log (2 : ℝ)) * ((1 : ℝ) * (Real.log (2 : ℝ) / Real.log (3 : ℝ))) - (1 : …` not stated: a numeral multiple of a fact (linear: Dafny's arithmetic scales it natively); Lean's premises: (-((((1.0 * Real.div(Real.log(3.0), Real.log(2.0))) * (1.0 * Real.div(Real.log(2.0), Real.log(3.0)))) - (1.0 * 1.0))) == 0.0); (2.0 > 0.0)
              // UNCITED-APPLIED Linarith.mul_eq: certificate piece `(2 : ℝ) * (-((1 : ℝ) * √(Real.log (2 : ℝ) / Real.log (3 : ℝ))) ^ (2 : ℕ) * ((1 : ℝ) * ((1 : ℝ) * √(Real.log (3 : ℝ) / R…` not stated: a numeral multiple of a fact (linear: Dafny's arithmetic scales it natively); Lean's premises: (-((((1.0 * Real.sqrt(Real.div(Real.log(2.0), Real.log(3.0)))) * (1.0 * Real.sqrt(Real.div(Real.log(2.0), Real.log(3.0))))) * ((1.0 * ((1.0 * Real.sqrt(Real.div(Real.log(3.0), Real.log(2.0)))) * (1.0 * Real.sqrt(Real.div(Real.log(3.0), Real.log(2.0)))))) - (1.0 * Real.div(Real.log(3.0), Real.log(2.0)))))) == 0.0); (2.0 > 0.0)
              // UNCITED-APPLIED Linarith.mul_eq: certificate piece `(2 : ℝ) * (-((1 : ℝ) * (Real.log (3 : ℝ) / Real.log (2 : ℝ))) * ((1 : ℝ) * ((1 : ℝ) * √(Real.log (2 : ℝ) / Real.log (3 …` not stated: a numeral multiple of a fact (linear: Dafny's arithmetic scales it natively); Lean's premises: (-(((1.0 * Real.div(Real.log(3.0), Real.log(2.0))) * ((1.0 * ((1.0 * Real.sqrt(Real.div(Real.log(2.0), Real.log(3.0)))) * (1.0 * Real.sqrt(Real.div(Real.log(2.0), Real.log(3.0)))))) - (1.0 * Real.div(Real.log(2.0), Real.log(3.0)))))) == 0.0); (2.0 > 0.0)
              if (0.0 < ((1.0 * Real.sqrt(Real.div(Real.log(3.0), Real.log(2.0)))) * (1.0 * Real.sqrt(Real.div(Real.log(2.0), Real.log(3.0)))))) && (((1.0 * (((1.0 * Real.sqrt(Real.div(Real.log(3.0), Real.log(2.0)))) + (1.0 * Real.sqrt(Real.div(Real.log(2.0), Real.log(3.0))))) * ((1.0 * Real.sqrt(Real.div(Real.log(3.0), Real.log(2.0)))) + (1.0 * Real.sqrt(Real.div(Real.log(2.0), Real.log(3.0))))))) - (((1.0 * ((1.0 * Real.sqrt(Real.div(Real.log(3.0), Real.log(2.0)))) * (1.0 * Real.sqrt(Real.div(Real.log(3.0), Real.log(2.0)))))) + (1.0 * ((1.0 * Real.sqrt(Real.div(Real.log(2.0), Real.log(3.0)))) * (1.0 * Real.sqrt(Real.div(Real.log(2.0), Real.log(3.0))))))) + (1.0 * 2.0))) < 0.0) { cert_piece_10(); }  // cert: mul_pos_of_neg_of_neg
              // UNCITED-APPLIED Linarith.lt_of_lt_of_eq ×4: certificate sums not stated: partial sums (subterms of a larger recorded sum of this certificate), e.g. `(2 : ℝ) * -((1 : ℝ) * (Real.log (3 : ℝ) / Real.log (2 : ℝ)) * ((1 : ℝ) * (Real.log (2 : ℝ) / Real.log (3 : ℝ))) - (1 : …`
              // UNCITED-APPLIED Linarith.lt_of_eq_of_lt ×2: certificate sums not stated: partial sums (subterms of a larger recorded sum of this certificate), e.g. `(2 : ℝ) * -((1 : ℝ) * (Real.log (3 : ℝ) / Real.log (2 : ℝ)) * ((1 : ℝ) * (Real.log (2 : ℝ) / Real.log (3 : ℝ))) - (1 : …`
              cert_identity_11();  // cert: Left.add_neg
              cert_identity_12();  // cert: Left.add_neg
              // UNCITED-APPLIED internal ×54 [exec 956 5800-5885]: applications made inside the tactic's own automation, not stated — CancelDenoms.sub_subst ×5, sub_eq_zero_of_eq ×3, CancelDenoms.add_subst ×3, CancelDenoms.pow_subst ×3, neg_eq_zero ×3, CancelDenoms.mul_subst ×2, sub_neg_of_lt ×2, CancelDenoms.neg_subst ×2, neg_neg_of_pos ×2, mul_pos_of_neg_of_neg ×2, neg_nonpos_of_nonneg ×1; machinery/glue: Linarith.without_one_mul ×7, Linarith.mul_eq ×6, congrArg ×6, Linarith.lt_of_eq_of_lt ×2 (+4 more heads, ×5) (cited in this block, not counted here: sq_nonneg [Lean recorded ×1])
              // UNCITED-APPLIED internal ×8 [exec 958 5800-5885]: applications made inside the tactic's own automation, not stated — machinery/glue: Mathlib.Meta.NormNum.isNat_ofNat ×2, of_eq_true ×1, eq_true ×1, Mathlib.Meta.NormNum.isNat_eq_true ×1 (+3 more heads, ×3) (cited in this block, not counted here: Nat.cast_one [Lean recorded ×1])
              // UNCITED-APPLIED internal ×8 [exec 959 5800-5885]: applications made inside the tactic's own automation, not stated — machinery/glue: Mathlib.Meta.NormNum.isNat_ofNat ×2, of_eq_true ×1, eq_true ×1, Mathlib.Meta.NormNum.isNat_eq_true ×1 (+3 more heads, ×3) (cited in this block, not counted here: Nat.cast_one [Lean recorded ×1])
              // UNCITED-APPLIED internal ×8 [exec 960 5800-5885]: applications made inside the tactic's own automation, not stated — machinery/glue: Mathlib.Meta.NormNum.isNat_ofNat ×2, of_eq_true ×1, eq_true ×1, Mathlib.Meta.NormNum.isNat_eq_true ×1 (+3 more heads, ×3) (cited in this block, not counted here: Nat.cast_one [Lean recorded ×1])
              // UNCITED-APPLIED internal ×8 [exec 961 5800-5885]: applications made inside the tactic's own automation, not stated — machinery/glue: Mathlib.Meta.NormNum.isNat_ofNat ×2, of_eq_true ×1, eq_true ×1, Mathlib.Meta.NormNum.isNat_eq_true ×1 (+3 more heads, ×3) (cited in this block, not counted here: Nat.cast_one [Lean recorded ×1])
              // UNCITED-APPLIED internal ×5 [exec 970 5800-5885]: applications made inside the tactic's own automation, not stated — machinery/glue: Mathlib.Meta.NormNum.isNat_ofNat ×2, of_eq_true ×1, eq_true ×1, Mathlib.Meta.NormNum.isNat_lt_true ×1 (cited in this block, not counted here: Nat.cast_zero [Lean recorded ×1])
              // UNCITED-APPLIED internal ×8 [exec 962 5800-5885]: applications made inside the tactic's own automation, not stated — machinery/glue: Mathlib.Meta.NormNum.isNat_ofNat ×2, of_eq_true ×1, eq_true ×1, Mathlib.Meta.NormNum.isNat_eq_true ×1 (+3 more heads, ×3) (cited in this block, not counted here: Nat.cast_one [Lean recorded ×1])
              // UNCITED-APPLIED internal ×5 [exec 971 5800-5885]: applications made inside the tactic's own automation, not stated — machinery/glue: Mathlib.Meta.NormNum.isNat_ofNat ×2, of_eq_true ×1, eq_true ×1, Mathlib.Meta.NormNum.isNat_lt_true ×1 (cited in this block, not counted here: Nat.cast_zero [Lean recorded ×1])
              // UNCITED-APPLIED internal ×5 [exec 963 5800-5885]: applications made inside the tactic's own automation, not stated — machinery/glue: of_eq_true ×1, eq_true ×1, Mathlib.Meta.NormNum.isNat_eq_true ×1, Mathlib.Meta.NormNum.isNat_mul ×1 (+1 more heads, ×1) (cited in this block, not counted here: Nat.cast_one [Lean recorded ×1])
              // UNCITED-APPLIED internal ×8 [exec 964 5800-5885]: applications made inside the tactic's own automation, not stated — machinery/glue: Mathlib.Meta.NormNum.isNat_ofNat ×2, of_eq_true ×1, eq_true ×1, Mathlib.Meta.NormNum.isNat_eq_true ×1 (+3 more heads, ×3) (cited in this block, not counted here: Nat.cast_one [Lean recorded ×1])
              // UNCITED-APPLIED internal ×8 [exec 965 5800-5885]: applications made inside the tactic's own automation, not stated — machinery/glue: Mathlib.Meta.NormNum.isNat_ofNat ×2, of_eq_true ×1, eq_true ×1, Mathlib.Meta.NormNum.isNat_eq_true ×1 (+3 more heads, ×3) (cited in this block, not counted here: Nat.cast_one [Lean recorded ×1])
              // UNCITED-APPLIED internal ×8 [exec 973 5800-5885]: applications made inside the tactic's own automation, not stated — machinery/glue: Mathlib.Meta.NormNum.isNat_ofNat ×2, of_eq_true ×1, eq_true ×1, Mathlib.Meta.NormNum.isNat_eq_true ×1 (+3 more heads, ×3) (cited in this block, not counted here: Nat.cast_one [Lean recorded ×1])
              // UNCITED-APPLIED internal ×220 [exec 983 5800-5885]: applications made inside the tactic's own automation, not stated — machinery/glue: Mathlib.Tactic.Ring.mul_congr ×8, Mathlib.Tactic.Ring.add_mul ×8, Mathlib.Tactic.Ring.mul_add ×8, Mathlib.Tactic.Ring.mul_pf_left ×8 (+53 more heads, ×188) (cited in this block, not counted here: Nat.cast_one [Lean recorded ×1], Nat.cast_zero [Lean recorded ×1])
              // UNCITED-APPLIED internal ×5 [exec 966 5800-5885]: applications made inside the tactic's own automation, not stated — machinery/glue: of_eq_true ×1, eq_true ×1, Mathlib.Meta.NormNum.isNat_eq_true ×1, Mathlib.Meta.NormNum.isNat_mul ×1 (+1 more heads, ×1) (cited in this block, not counted here: Nat.cast_one [Lean recorded ×1])
              // UNCITED-APPLIED internal ×5 [exec 984 5800-5885]: applications made inside the tactic's own automation, not stated — machinery/glue: Mathlib.Meta.NormNum.isNat_ofNat ×2, of_eq_true ×1, eq_true ×1, Mathlib.Meta.NormNum.isNat_lt_true ×1 (cited in this block, not counted here: Nat.cast_zero [Lean recorded ×1])
              // UNCITED-APPLIED internal ×8 [exec 974 5800-5885]: applications made inside the tactic's own automation, not stated — machinery/glue: Mathlib.Meta.NormNum.isNat_ofNat ×2, of_eq_true ×1, eq_true ×1, Mathlib.Meta.NormNum.isNat_eq_true ×1 (+3 more heads, ×3) (cited in this block, not counted here: Nat.cast_one [Lean recorded ×1])
              // UNCITED-APPLIED internal ×8 [exec 975 5800-5885]: applications made inside the tactic's own automation, not stated — machinery/glue: Mathlib.Meta.NormNum.isNat_ofNat ×2, of_eq_true ×1, eq_true ×1, Mathlib.Meta.NormNum.isNat_eq_true ×1 (+3 more heads, ×3) (cited in this block, not counted here: Nat.cast_one [Lean recorded ×1])
              // UNCITED-APPLIED internal ×8 [exec 976 5800-5885]: applications made inside the tactic's own automation, not stated — machinery/glue: Mathlib.Meta.NormNum.isNat_ofNat ×2, of_eq_true ×1, eq_true ×1, Mathlib.Meta.NormNum.isNat_eq_true ×1 (+3 more heads, ×3) (cited in this block, not counted here: Nat.cast_one [Lean recorded ×1])
              // UNCITED-APPLIED internal ×8 [exec 977 5800-5885]: applications made inside the tactic's own automation, not stated — machinery/glue: Mathlib.Meta.NormNum.isNat_ofNat ×2, of_eq_true ×1, eq_true ×1, Mathlib.Meta.NormNum.isNat_eq_true ×1 (+3 more heads, ×3) (cited in this block, not counted here: Nat.cast_one [Lean recorded ×1])
              // UNCITED-APPLIED internal ×5 [exec 985 5800-5885]: applications made inside the tactic's own automation, not stated — machinery/glue: Mathlib.Meta.NormNum.isNat_ofNat ×2, of_eq_true ×1, eq_true ×1, Mathlib.Meta.NormNum.isNat_lt_true ×1 (cited in this block, not counted here: Nat.cast_zero [Lean recorded ×1])
              // UNCITED-APPLIED internal ×8 [exec 979 5800-5885]: applications made inside the tactic's own automation, not stated — machinery/glue: Mathlib.Meta.NormNum.isNat_ofNat ×2, of_eq_true ×1, eq_true ×1, Mathlib.Meta.NormNum.isNat_eq_true ×1 (+3 more heads, ×3) (cited in this block, not counted here: Nat.cast_one [Lean recorded ×1])
              // UNCITED-APPLIED internal ×5 [exec 986 5800-5885]: applications made inside the tactic's own automation, not stated — machinery/glue: Mathlib.Meta.NormNum.isNat_ofNat ×2, of_eq_true ×1, eq_true ×1, Mathlib.Meta.NormNum.isNat_lt_true ×1 (cited in this block, not counted here: Nat.cast_zero [Lean recorded ×1])
              // UNCITED-APPLIED internal ×5 [exec 967 5800-5885]: applications made inside the tactic's own automation, not stated — machinery/glue: of_eq_true ×1, eq_true ×1, Mathlib.Meta.NormNum.isNat_eq_true ×1, Mathlib.Meta.NormNum.isNat_mul ×1 (+1 more heads, ×1) (cited in this block, not counted here: Nat.cast_one [Lean recorded ×1])
              // UNCITED-APPLIED internal ×8 [exec 980 5800-5885]: applications made inside the tactic's own automation, not stated — machinery/glue: Mathlib.Meta.NormNum.isNat_ofNat ×2, of_eq_true ×1, eq_true ×1, Mathlib.Meta.NormNum.isNat_eq_true ×1 (+3 more heads, ×3) (cited in this block, not counted here: Nat.cast_one [Lean recorded ×1])
              // NOT APPLIED Real.sq_sqrt: named here, but Lean's proof at this tactic does not apply it (applied only at other tactics of the proof)
              // NOT APPLIED le_of_lt: named here, but Lean's proof at this tactic does not apply it (applied only at other tactics of the proof)
              NatCastOne();  // cite: Nat.cast_one [applied by the tactic, not named in it: inside its internal steps (`normNum` exec 957, 958, 959, 960, 961, 962 … / `ring1` exec 968, 983)]
              NatCastZero();  // cite: Nat.cast_zero [applied by the tactic, not named in it: inside its internal steps (`normNum` exec 969, 970, 971, 984, 985, 986 / `ring1` exec 968, 983)]
              SqNonneg((1.0 * Real.sqrt(Real.div(Real.log(2.0), Real.log(3.0)))));  // cite: sq_nonneg [applied by the tactic, not named in it]
              // UNCITED-APPLIED internal ×221 [exec 968 5800-5885]: applications made inside the tactic's own automation, not stated — machinery/glue: Mathlib.Tactic.Ring.mul_congr ×8, Mathlib.Tactic.Ring.add_mul ×8, Mathlib.Tactic.Ring.mul_add ×8, Mathlib.Tactic.Ring.mul_pf_left ×8 (+53 more heads, ×189) (cited in this block, not counted here: Nat.cast_one [Lean recorded ×1], Nat.cast_zero [Lean recorded ×1])
              // UNCITED-APPLIED internal ×5 [exec 957 5800-5885]: applications made inside the tactic's own automation, not stated — machinery/glue: of_eq_true ×1, eq_true ×1, Mathlib.Meta.NormNum.isNat_eq_true ×1, Mathlib.Meta.NormNum.isNat_mul ×1 (+1 more heads, ×1) (cited in this block, not counted here: Nat.cast_one [Lean recorded ×1])
              // UNCITED-APPLIED internal ×5 [exec 969 5800-5885]: applications made inside the tactic's own automation, not stated — machinery/glue: Mathlib.Meta.NormNum.isNat_ofNat ×2, of_eq_true ×1, eq_true ×1, Mathlib.Meta.NormNum.isNat_lt_true ×1 (cited in this block, not counted here: Nat.cast_zero [Lean recorded ×1])
}

