// NOT CLOSED — failing line imo_1965_p1-1222: theorem imo_1965_p1, Dafny line 1222 (OOR: Verification out of resource (imo_1965_p1))
// failing Dafny line: assert (((Real.sqrt((1.0 - Real.sin((2.0 * x)))) - Real.sqrt((1.0 + Real.sin((2.0 * x))))) * (Real.sqrt((1.0 - Real.sin((2.0 * x)))) - Real.sqrt((1.0 + Real.sin((2.0 * x)))))) == (2.0 + (2.0 * Real.co
// Lean step: nlinarith [Real.sq_sqrt (show 0 ≤ 1 + Real.sin (2 * x) by nlinarith [Real.sin_le_one (2 * x), Real.neg_one_le_sin (2 * x)]),
// hypotheses: 53 facts Z3 had at the line (goal itself removed: 0; the block's own asserts removed: 3); nothing assumed beyond the facts in scope
// not closed: tried H0=failed, K2=failed, simplest_call=oor; this file is the honest base attempt
// Dafny: finished with 27 verified, 1 error  (flags: dafny verify --isolate-assertions --resource-limit 1000000 --allow-warnings --cores 1, timeout 30 s)

include "../dafny/imo_1965_p1.dfy"
lemma {:induction false} vc_imo_1965_p1_L1222(x: real)
  requires 0.0 <= x
  requires x <= 2.0 * Real.pi()
  requires 2.0 * Real.cos(x) <= abs(Real.sqrt(1.0 + Real.sin(2.0 * x)) - Real.sqrt(1.0 - Real.sin(2.0 * x)))
  requires abs(Real.sqrt(1.0 + Real.sin(2.0 * x)) - Real.sqrt(1.0 - Real.sin(2.0 * x))) <= Real.sqrt(2.0)
  requires 0.0 <= Real.sqrt(1.0 + Real.sin(2.0 * x))
  requires 0.0 <= Real.sqrt(1.0 - Real.sin(2.0 * x))
  requires 0.0 <= Real.sqrt(2.0)
  requires 0.0 <= Real.sqrt(1.0 + Real.sin(2.0 * x)) * Real.sqrt(1.0 - Real.sin(2.0 * x))
  requires 0.0 <= Real.cos(2.0 * x) || Real.cos(2.0 * x) <= 0.0
  requires ((0.0 <= Real.cos(2.0 * x)) && (((0.0 <= Real.sqrt(1.0 + Real.sin(2.0 * x)) - Real.sqrt(1.0 - Real.sin(2.0 * x))) && (((0.0 <= Real.sqrt(1.0 + Real.sin(2.0 * x)) - Real.sqrt(1.0 - Real.sin(2.0 * x))) && (Real.abs(Real.sqrt(1.0 + Real.sin(2.0 * x)) - Real.sqrt(1.0 - Real.sin(2.0 * x))) == Real.sqrt(1.0 + Real.sin(2.0 * x)) - Real.sqrt(1.0 - Real.sin(2.0 * x)))) || (Real.sqrt(1.0 + Real.sin(2.0 * x)) - Real.sqrt(1.0 - Real.sin(2.0 * x)) < 0.0)) && (((0.0 <= Real.cos(2.0 * x)) && (Real.abs(Real.cos(2.0 * x)) == Real.cos(2.0 * x))) || (Real.cos(2.0 * x) < 0.0)) && (2.0 * Real.cos(x) <= Real.sqrt(1.0 + Real.sin(2.0 * x)) - Real.sqrt(1.0 - Real.sin(2.0 * x))) && (Real.sqrt(1.0 + Real.sin(2.0 * x)) <= Real.sqrt(2.0) + Real.sqrt(1.0 - Real.sin(2.0 * x))) && (Real.sqrt(1.0 - Real.sin(2.0 * x)) <= Real.sqrt(1.0 + Real.sin(2.0 * x))) && ((Real.sqrt(1.0 + Real.sin(2.0 * x)) - Real.sqrt(1.0 - Real.sin(2.0 * x))) * (Real.sqrt(1.0 + Real.sin(2.0 * x)) - Real.sqrt(1.0 - Real.sin(2.0 * x))) == 2.0 - 2.0 * Real.cos(2.0 * x)) && (abs(Real.sqrt(1.0 + Real.sin(2.0 * x)) - Real.sqrt(1.0 - Real.sin(2.0 * x))) * abs(Real.sqrt(1.0 + Real.sin(2.0 * x)) - Real.sqrt(1.0 - Real.sin(2.0 * x))) == 2.0 - 2.0 * abs(Real.cos(2.0 * x)))) || (Real.sqrt(1.0 + Real.sin(2.0 * x)) - Real.sqrt(1.0 - Real.sin(2.0 * x)) < 0.0)) && (((Real.sqrt(1.0 + Real.sin(2.0 * x)) - Real.sqrt(1.0 - Real.sin(2.0 * x)) <= 0.0) && (((0.0 <= Real.cos(2.0 * x)) && (Real.abs(Real.cos(2.0 * x)) == Real.cos(2.0 * x))) || (Real.cos(2.0 * x) < 0.0)) && (((Real.sqrt(1.0 + Real.sin(2.0 * x)) - Real.sqrt(1.0 - Real.sin(2.0 * x)) <= 0.0) && (Real.abs(Real.sqrt(1.0 + Real.sin(2.0 * x)) - Real.sqrt(1.0 - Real.sin(2.0 * x))) == 0.0 - (Real.sqrt(1.0 + Real.sin(2.0 * x)) - Real.sqrt(1.0 - Real.sin(2.0 * x))))) || (0.0 < Real.sqrt(1.0 + Real.sin(2.0 * x)) - Real.sqrt(1.0 - Real.sin(2.0 * x)))) && (2.0 * Real.cos(x) <= Real.sqrt(1.0 - Real.sin(2.0 * x)) - Real.sqrt(1.0 + Real.sin(2.0 * x))) && (Real.sqrt(1.0 - Real.sin(2.0 * x)) <= Real.sqrt(2.0) + Real.sqrt(1.0 + Real.sin(2.0 * x))) && (Real.sqrt(1.0 + Real.sin(2.0 * x)) <= Real.sqrt(1.0 - Real.sin(2.0 * x))) && ((Real.sqrt(1.0 - Real.sin(2.0 * x)) - Real.sqrt(1.0 + Real.sin(2.0 * x))) * (Real.sqrt(1.0 - Real.sin(2.0 * x)) - Real.sqrt(1.0 + Real.sin(2.0 * x))) == 2.0 - 2.0 * Real.cos(2.0 * x)) && (abs(Real.sqrt(1.0 + Real.sin(2.0 * x)) - Real.sqrt(1.0 - Real.sin(2.0 * x))) * abs(Real.sqrt(1.0 + Real.sin(2.0 * x)) - Real.sqrt(1.0 - Real.sin(2.0 * x))) == 2.0 - 2.0 * abs(Real.cos(2.0 * x)))) || (0.0 < Real.sqrt(1.0 + Real.sin(2.0 * x)) - Real.sqrt(1.0 - Real.sin(2.0 * x)))) && (0.0 <= Real.sqrt(1.0 + Real.sin(2.0 * x)) - Real.sqrt(1.0 - Real.sin(2.0 * x)) || Real.sqrt(1.0 + Real.sin(2.0 * x)) - Real.sqrt(1.0 - Real.sin(2.0 * x)) <= 0.0) && (abs(Real.sqrt(1.0 + Real.sin(2.0 * x)) - Real.sqrt(1.0 - Real.sin(2.0 * x))) * abs(Real.sqrt(1.0 + Real.sin(2.0 * x)) - Real.sqrt(1.0 - Real.sin(2.0 * x))) == 2.0 - 2.0 * abs(Real.cos(2.0 * x)))) || (Real.cos(2.0 * x) < 0.0)
  requires Real.cos(2.0 * x) <= 0.0
  requires ((0.0 <= Real.sqrt(1.0 + Real.sin(2.0 * x)) - Real.sqrt(1.0 - Real.sin(2.0 * x))) && (((0.0 <= Real.sqrt(1.0 + Real.sin(2.0 * x)) - Real.sqrt(1.0 - Real.sin(2.0 * x))) && (Real.abs(Real.sqrt(1.0 + Real.sin(2.0 * x)) - Real.sqrt(1.0 - Real.sin(2.0 * x))) == Real.sqrt(1.0 + Real.sin(2.0 * x)) - Real.sqrt(1.0 - Real.sin(2.0 * x)))) || (Real.sqrt(1.0 + Real.sin(2.0 * x)) - Real.sqrt(1.0 - Real.sin(2.0 * x)) < 0.0)) && (((Real.cos(2.0 * x) <= 0.0) && (Real.abs(Real.cos(2.0 * x)) == 0.0 - Real.cos(2.0 * x))) || (0.0 < Real.cos(2.0 * x))) && (2.0 * Real.cos(x) <= Real.sqrt(1.0 + Real.sin(2.0 * x)) - Real.sqrt(1.0 - Real.sin(2.0 * x))) && (Real.sqrt(1.0 + Real.sin(2.0 * x)) <= Real.sqrt(2.0) + Real.sqrt(1.0 - Real.sin(2.0 * x))) && (Real.sqrt(1.0 - Real.sin(2.0 * x)) <= Real.sqrt(1.0 + Real.sin(2.0 * x))) && ((Real.sqrt(1.0 + Real.sin(2.0 * x)) - Real.sqrt(1.0 - Real.sin(2.0 * x))) * (Real.sqrt(1.0 + Real.sin(2.0 * x)) - Real.sqrt(1.0 - Real.sin(2.0 * x))) == 2.0 + 2.0 * Real.cos(2.0 * x)) && (abs(Real.sqrt(1.0 + Real.sin(2.0 * x)) - Real.sqrt(1.0 - Real.sin(2.0 * x))) * abs(Real.sqrt(1.0 + Real.sin(2.0 * x)) - Real.sqrt(1.0 - Real.sin(2.0 * x))) == 2.0 - 2.0 * abs(Real.cos(2.0 * x)))) || (Real.sqrt(1.0 + Real.sin(2.0 * x)) - Real.sqrt(1.0 - Real.sin(2.0 * x)) < 0.0)
  requires Real.sqrt(1.0 + Real.sin(2.0 * x)) - Real.sqrt(1.0 - Real.sin(2.0 * x)) <= 0.0
  requires ((Real.sqrt(1.0 + Real.sin(2.0 * x)) - Real.sqrt(1.0 - Real.sin(2.0 * x)) <= 0.0) && (Real.abs(Real.sqrt(1.0 + Real.sin(2.0 * x)) - Real.sqrt(1.0 - Real.sin(2.0 * x))) == 0.0 - (Real.sqrt(1.0 + Real.sin(2.0 * x)) - Real.sqrt(1.0 - Real.sin(2.0 * x))))) || (0.0 < Real.sqrt(1.0 + Real.sin(2.0 * x)) - Real.sqrt(1.0 - Real.sin(2.0 * x)))
  requires ((Real.cos(2.0 * x) <= 0.0) && (Real.abs(Real.cos(2.0 * x)) == 0.0 - Real.cos(2.0 * x))) || (0.0 < Real.cos(2.0 * x))
  requires 2.0 * Real.cos(x) <= Real.sqrt(1.0 - Real.sin(2.0 * x)) - Real.sqrt(1.0 + Real.sin(2.0 * x))
  requires Real.sqrt(1.0 - Real.sin(2.0 * x)) <= Real.sqrt(2.0) + Real.sqrt(1.0 + Real.sin(2.0 * x))
  requires Real.sqrt(1.0 + Real.sin(2.0 * x)) <= Real.sqrt(1.0 - Real.sin(2.0 * x))
  requires Real.cos(2.0 * x) * Real.cos(2.0 * x) + Real.sin(2.0 * x) * Real.sin(2.0 * x) == 1.0
  requires (1 as real) == 1.0
  requires (0 as real) == 0.0
  requires 0.0 <= Real.sqrt(1.0 - Real.sin(2.0 * x)) * Real.sqrt(1.0 - Real.sin(2.0 * x))
  requires 0.0 <= (Real.sqrt(1.0 - Real.sin(2.0 * x)) - Real.sqrt(1.0 + Real.sin(2.0 * x))) * (Real.sqrt(1.0 - Real.sin(2.0 * x)) - Real.sqrt(1.0 + Real.sin(2.0 * x)))
  requires 0.0 <= Real.sqrt(1.0 + Real.sin(2.0 * x)) * Real.sqrt(1.0 + Real.sin(2.0 * x))
  requires (((Real.sqrt(1.0 - Real.sin(2.0 * x)) - Real.sqrt(1.0 + Real.sin(2.0 * x))) * (Real.sqrt(1.0 - Real.sin(2.0 * x)) - Real.sqrt(1.0 + Real.sin(2.0 * x))) - (2.0 + 2.0 * Real.cos(2.0 * x)) < 0.0) && ((Real.sqrt(1.0 - Real.sin(2.0 * x)) - Real.sqrt(1.0 + Real.sin(2.0 * x))) * (Real.sqrt(1.0 - Real.sin(2.0 * x)) - Real.sqrt(1.0 + Real.sin(2.0 * x))) - (2.0 + 2.0 * Real.cos(2.0 * x)) < 0.0) && ((Real.sqrt(1.0 - Real.sin(2.0 * x)) - Real.sqrt(1.0 + Real.sin(2.0 * x))) * (Real.sqrt(1.0 - Real.sin(2.0 * x)) - Real.sqrt(1.0 + Real.sin(2.0 * x))) - (2.0 + 2.0 * Real.cos(2.0 * x)) <= 0.0)) || (0.0 <= (Real.sqrt(1.0 - Real.sin(2.0 * x)) - Real.sqrt(1.0 + Real.sin(2.0 * x))) * (Real.sqrt(1.0 - Real.sin(2.0 * x)) - Real.sqrt(1.0 + Real.sin(2.0 * x))) - (2.0 + 2.0 * Real.cos(2.0 * x)))
  requires ((2.0 + 2.0 * Real.cos(2.0 * x) - (Real.sqrt(1.0 - Real.sin(2.0 * x)) - Real.sqrt(1.0 + Real.sin(2.0 * x))) * (Real.sqrt(1.0 - Real.sin(2.0 * x)) - Real.sqrt(1.0 + Real.sin(2.0 * x))) < 0.0) && (2.0 + 2.0 * Real.cos(2.0 * x) - (Real.sqrt(1.0 - Real.sin(2.0 * x)) - Real.sqrt(1.0 + Real.sin(2.0 * x))) * (Real.sqrt(1.0 - Real.sin(2.0 * x)) - Real.sqrt(1.0 + Real.sin(2.0 * x))) < 0.0) && (2.0 + 2.0 * Real.cos(2.0 * x) - (Real.sqrt(1.0 - Real.sin(2.0 * x)) - Real.sqrt(1.0 + Real.sin(2.0 * x))) * (Real.sqrt(1.0 - Real.sin(2.0 * x)) - Real.sqrt(1.0 + Real.sin(2.0 * x))) <= 0.0)) || (0.0 <= 2.0 + 2.0 * Real.cos(2.0 * x) - (Real.sqrt(1.0 - Real.sin(2.0 * x)) - Real.sqrt(1.0 + Real.sin(2.0 * x))) * (Real.sqrt(1.0 - Real.sin(2.0 * x)) - Real.sqrt(1.0 + Real.sin(2.0 * x))))
  requires Real.sqrt(1.0 - Real.sin(2.0 * x)) * Real.sqrt(1.0 - Real.sin(2.0 * x)) == 1.0 - Real.sin(2.0 * x)
  requires Real.sqrt(1.0 + Real.sin(2.0 * x)) * Real.sqrt(1.0 + Real.sin(2.0 * x)) == 1.0 + Real.sin(2.0 * x)
  requires (0.0 <= Real.sqrt(1.0 - Real.sin(2.0 * x)) * Real.sqrt(1.0 - Real.sin(2.0 * x))) || (Real.sqrt(1.0 - Real.sin(2.0 * x)) * Real.sqrt(1.0 - Real.sin(2.0 * x)) < 0.0)
  requires ((0.0 <= Real.sqrt(1.0 - Real.sin(2.0 * x)) * Real.sqrt(1.0 - Real.sin(2.0 * x))) && (Real.sqrt(1.0 + Real.sin(2.0 * x)) * Real.sqrt(1.0 + Real.sin(2.0 * x)) - (1.0 + Real.sin(2.0 * x)) == 0.0) && (0.0 - Real.sqrt(1.0 - Real.sin(2.0 * x)) * Real.sqrt(1.0 - Real.sin(2.0 * x)) * (Real.sqrt(1.0 + Real.sin(2.0 * x)) * Real.sqrt(1.0 + Real.sin(2.0 * x)) - (1.0 + Real.sin(2.0 * x))) == 0.0)) || (!(0.0 <= Real.sqrt(1.0 - Real.sin(2.0 * x)) * Real.sqrt(1.0 - Real.sin(2.0 * x)) && Real.sqrt(1.0 + Real.sin(2.0 * x)) * Real.sqrt(1.0 + Real.sin(2.0 * x)) - (1.0 + Real.sin(2.0 * x)) == 0.0))
  requires (0.0 <= Real.sqrt(1.0 - Real.sin(2.0 * x)) * Real.sqrt(1.0 - Real.sin(2.0 * x))) || (Real.sqrt(1.0 - Real.sin(2.0 * x)) * Real.sqrt(1.0 - Real.sin(2.0 * x)) < 0.0)
  requires ((0.0 <= Real.sqrt(1.0 - Real.sin(2.0 * x)) * Real.sqrt(1.0 - Real.sin(2.0 * x))) && (Real.sqrt(1.0 - Real.sin(2.0 * x)) * Real.sqrt(1.0 - Real.sin(2.0 * x)) - (1.0 - Real.sin(2.0 * x)) == 0.0) && (0.0 - Real.sqrt(1.0 - Real.sin(2.0 * x)) * Real.sqrt(1.0 - Real.sin(2.0 * x)) * (Real.sqrt(1.0 - Real.sin(2.0 * x)) * Real.sqrt(1.0 - Real.sin(2.0 * x)) - (1.0 - Real.sin(2.0 * x))) == 0.0)) || (!(0.0 <= Real.sqrt(1.0 - Real.sin(2.0 * x)) * Real.sqrt(1.0 - Real.sin(2.0 * x)) && Real.sqrt(1.0 - Real.sin(2.0 * x)) * Real.sqrt(1.0 - Real.sin(2.0 * x)) - (1.0 - Real.sin(2.0 * x)) == 0.0))
  requires (0.0 <= (Real.sqrt(1.0 - Real.sin(2.0 * x)) - Real.sqrt(1.0 + Real.sin(2.0 * x))) * (Real.sqrt(1.0 - Real.sin(2.0 * x)) - Real.sqrt(1.0 + Real.sin(2.0 * x)))) || ((Real.sqrt(1.0 - Real.sin(2.0 * x)) - Real.sqrt(1.0 + Real.sin(2.0 * x))) * (Real.sqrt(1.0 - Real.sin(2.0 * x)) - Real.sqrt(1.0 + Real.sin(2.0 * x))) < 0.0)
  requires ((0.0 <= (Real.sqrt(1.0 - Real.sin(2.0 * x)) - Real.sqrt(1.0 + Real.sin(2.0 * x))) * (Real.sqrt(1.0 - Real.sin(2.0 * x)) - Real.sqrt(1.0 + Real.sin(2.0 * x)))) && (Real.sqrt(1.0 + Real.sin(2.0 * x)) * Real.sqrt(1.0 + Real.sin(2.0 * x)) - (1.0 + Real.sin(2.0 * x)) == 0.0) && (0.0 - (Real.sqrt(1.0 - Real.sin(2.0 * x)) - Real.sqrt(1.0 + Real.sin(2.0 * x))) * (Real.sqrt(1.0 - Real.sin(2.0 * x)) - Real.sqrt(1.0 + Real.sin(2.0 * x))) * (Real.sqrt(1.0 + Real.sin(2.0 * x)) * Real.sqrt(1.0 + Real.sin(2.0 * x)) - (1.0 + Real.sin(2.0 * x))) == 0.0)) || (!(0.0 <= (Real.sqrt(1.0 - Real.sin(2.0 * x)) - Real.sqrt(1.0 + Real.sin(2.0 * x))) * (Real.sqrt(1.0 - Real.sin(2.0 * x)) - Real.sqrt(1.0 + Real.sin(2.0 * x))) && Real.sqrt(1.0 + Real.sin(2.0 * x)) * Real.sqrt(1.0 + Real.sin(2.0 * x)) - (1.0 + Real.sin(2.0 * x)) == 0.0))
  requires (0.0 <= (Real.sqrt(1.0 - Real.sin(2.0 * x)) - Real.sqrt(1.0 + Real.sin(2.0 * x))) * (Real.sqrt(1.0 - Real.sin(2.0 * x)) - Real.sqrt(1.0 + Real.sin(2.0 * x)))) || ((Real.sqrt(1.0 - Real.sin(2.0 * x)) - Real.sqrt(1.0 + Real.sin(2.0 * x))) * (Real.sqrt(1.0 - Real.sin(2.0 * x)) - Real.sqrt(1.0 + Real.sin(2.0 * x))) < 0.0)
  requires ((0.0 <= (Real.sqrt(1.0 - Real.sin(2.0 * x)) - Real.sqrt(1.0 + Real.sin(2.0 * x))) * (Real.sqrt(1.0 - Real.sin(2.0 * x)) - Real.sqrt(1.0 + Real.sin(2.0 * x)))) && (Real.sqrt(1.0 - Real.sin(2.0 * x)) * Real.sqrt(1.0 - Real.sin(2.0 * x)) - (1.0 - Real.sin(2.0 * x)) == 0.0) && (0.0 - (Real.sqrt(1.0 - Real.sin(2.0 * x)) - Real.sqrt(1.0 + Real.sin(2.0 * x))) * (Real.sqrt(1.0 - Real.sin(2.0 * x)) - Real.sqrt(1.0 + Real.sin(2.0 * x))) * (Real.sqrt(1.0 - Real.sin(2.0 * x)) * Real.sqrt(1.0 - Real.sin(2.0 * x)) - (1.0 - Real.sin(2.0 * x))) == 0.0)) || (!(0.0 <= (Real.sqrt(1.0 - Real.sin(2.0 * x)) - Real.sqrt(1.0 + Real.sin(2.0 * x))) * (Real.sqrt(1.0 - Real.sin(2.0 * x)) - Real.sqrt(1.0 + Real.sin(2.0 * x))) && Real.sqrt(1.0 - Real.sin(2.0 * x)) * Real.sqrt(1.0 - Real.sin(2.0 * x)) - (1.0 - Real.sin(2.0 * x)) == 0.0))
  requires (0.0 <= Real.sqrt(1.0 + Real.sin(2.0 * x)) * Real.sqrt(1.0 + Real.sin(2.0 * x))) || (Real.sqrt(1.0 + Real.sin(2.0 * x)) * Real.sqrt(1.0 + Real.sin(2.0 * x)) < 0.0)
  requires ((0.0 <= Real.sqrt(1.0 + Real.sin(2.0 * x)) * Real.sqrt(1.0 + Real.sin(2.0 * x))) && (Real.sqrt(1.0 + Real.sin(2.0 * x)) * Real.sqrt(1.0 + Real.sin(2.0 * x)) - (1.0 + Real.sin(2.0 * x)) == 0.0) && (0.0 - Real.sqrt(1.0 + Real.sin(2.0 * x)) * Real.sqrt(1.0 + Real.sin(2.0 * x)) * (Real.sqrt(1.0 + Real.sin(2.0 * x)) * Real.sqrt(1.0 + Real.sin(2.0 * x)) - (1.0 + Real.sin(2.0 * x))) == 0.0)) || (!(0.0 <= Real.sqrt(1.0 + Real.sin(2.0 * x)) * Real.sqrt(1.0 + Real.sin(2.0 * x)) && Real.sqrt(1.0 + Real.sin(2.0 * x)) * Real.sqrt(1.0 + Real.sin(2.0 * x)) - (1.0 + Real.sin(2.0 * x)) == 0.0))
  requires (0.0 <= Real.sqrt(1.0 + Real.sin(2.0 * x)) * Real.sqrt(1.0 + Real.sin(2.0 * x))) || (Real.sqrt(1.0 + Real.sin(2.0 * x)) * Real.sqrt(1.0 + Real.sin(2.0 * x)) < 0.0)
  requires ((0.0 <= Real.sqrt(1.0 + Real.sin(2.0 * x)) * Real.sqrt(1.0 + Real.sin(2.0 * x))) && (Real.sqrt(1.0 - Real.sin(2.0 * x)) * Real.sqrt(1.0 - Real.sin(2.0 * x)) - (1.0 - Real.sin(2.0 * x)) == 0.0) && (0.0 - Real.sqrt(1.0 + Real.sin(2.0 * x)) * Real.sqrt(1.0 + Real.sin(2.0 * x)) * (Real.sqrt(1.0 - Real.sin(2.0 * x)) * Real.sqrt(1.0 - Real.sin(2.0 * x)) - (1.0 - Real.sin(2.0 * x))) == 0.0)) || (!(0.0 <= Real.sqrt(1.0 + Real.sin(2.0 * x)) * Real.sqrt(1.0 + Real.sin(2.0 * x)) && Real.sqrt(1.0 - Real.sin(2.0 * x)) * Real.sqrt(1.0 - Real.sin(2.0 * x)) - (1.0 - Real.sin(2.0 * x)) == 0.0))
  requires (Real.cos(2.0 * x) <= 0.0) || (0.0 < Real.cos(2.0 * x))
  requires ((Real.cos(2.0 * x) <= 0.0) && ((Real.sqrt(1.0 - Real.sin(2.0 * x)) - Real.sqrt(1.0 + Real.sin(2.0 * x))) * (Real.sqrt(1.0 - Real.sin(2.0 * x)) - Real.sqrt(1.0 + Real.sin(2.0 * x))) - (2.0 + 2.0 * Real.cos(2.0 * x)) <= 0.0) && (0.0 <= Real.cos(2.0 * x) * ((Real.sqrt(1.0 - Real.sin(2.0 * x)) - Real.sqrt(1.0 + Real.sin(2.0 * x))) * (Real.sqrt(1.0 - Real.sin(2.0 * x)) - Real.sqrt(1.0 + Real.sin(2.0 * x))) - (2.0 + 2.0 * Real.cos(2.0 * x))))) || (!(Real.cos(2.0 * x) <= 0.0 && (Real.sqrt(1.0 - Real.sin(2.0 * x)) - Real.sqrt(1.0 + Real.sin(2.0 * x))) * (Real.sqrt(1.0 - Real.sin(2.0 * x)) - Real.sqrt(1.0 + Real.sin(2.0 * x))) - (2.0 + 2.0 * Real.cos(2.0 * x)) <= 0.0))
  requires (((Real.sqrt(1.0 - Real.sin(2.0 * x)) - Real.sqrt(1.0 + Real.sin(2.0 * x))) * (Real.sqrt(1.0 - Real.sin(2.0 * x)) - Real.sqrt(1.0 + Real.sin(2.0 * x))) - (2.0 + 2.0 * Real.cos(2.0 * x)) < 0.0) && (0.0 < ((Real.sqrt(1.0 - Real.sin(2.0 * x)) - Real.sqrt(1.0 + Real.sin(2.0 * x))) * (Real.sqrt(1.0 - Real.sin(2.0 * x)) - Real.sqrt(1.0 + Real.sin(2.0 * x))) - (2.0 + 2.0 * Real.cos(2.0 * x))) * ((Real.sqrt(1.0 - Real.sin(2.0 * x)) - Real.sqrt(1.0 + Real.sin(2.0 * x))) * (Real.sqrt(1.0 - Real.sin(2.0 * x)) - Real.sqrt(1.0 + Real.sin(2.0 * x))) - (2.0 + 2.0 * Real.cos(2.0 * x))))) || (0.0 <= (Real.sqrt(1.0 - Real.sin(2.0 * x)) - Real.sqrt(1.0 + Real.sin(2.0 * x))) * (Real.sqrt(1.0 - Real.sin(2.0 * x)) - Real.sqrt(1.0 + Real.sin(2.0 * x))) - (2.0 + 2.0 * Real.cos(2.0 * x)))
  requires ((Real.sqrt(1.0 + Real.sin(2.0 * x)) * Real.sqrt(1.0 + Real.sin(2.0 * x)) - (1.0 + Real.sin(2.0 * x)) == 0.0) && ((Real.sqrt(1.0 + Real.sin(2.0 * x)) * Real.sqrt(1.0 + Real.sin(2.0 * x)) - (1.0 + Real.sin(2.0 * x))) * (Real.sqrt(1.0 + Real.sin(2.0 * x)) * Real.sqrt(1.0 + Real.sin(2.0 * x)) - (1.0 + Real.sin(2.0 * x))) == 0.0)) || (Real.sqrt(1.0 + Real.sin(2.0 * x)) * Real.sqrt(1.0 + Real.sin(2.0 * x)) - (1.0 + Real.sin(2.0 * x)) != 0.0)
  requires (0.0 <= Real.sqrt(1.0 + Real.sin(2.0 * x)) * Real.sqrt(1.0 - Real.sin(2.0 * x))) || (Real.sqrt(1.0 + Real.sin(2.0 * x)) * Real.sqrt(1.0 - Real.sin(2.0 * x)) < 0.0)
  requires ((0.0 <= Real.sqrt(1.0 + Real.sin(2.0 * x)) * Real.sqrt(1.0 - Real.sin(2.0 * x))) && (2.0 + 2.0 * Real.cos(2.0 * x) - (Real.sqrt(1.0 - Real.sin(2.0 * x)) - Real.sqrt(1.0 + Real.sin(2.0 * x))) * (Real.sqrt(1.0 - Real.sin(2.0 * x)) - Real.sqrt(1.0 + Real.sin(2.0 * x))) <= 0.0) && (Real.sqrt(1.0 + Real.sin(2.0 * x)) * Real.sqrt(1.0 - Real.sin(2.0 * x)) * (2.0 + 2.0 * Real.cos(2.0 * x) - (Real.sqrt(1.0 - Real.sin(2.0 * x)) - Real.sqrt(1.0 + Real.sin(2.0 * x))) * (Real.sqrt(1.0 - Real.sin(2.0 * x)) - Real.sqrt(1.0 + Real.sin(2.0 * x)))) <= 0.0)) || (!(0.0 <= Real.sqrt(1.0 + Real.sin(2.0 * x)) * Real.sqrt(1.0 - Real.sin(2.0 * x)) && 2.0 + 2.0 * Real.cos(2.0 * x) - (Real.sqrt(1.0 - Real.sin(2.0 * x)) - Real.sqrt(1.0 + Real.sin(2.0 * x))) * (Real.sqrt(1.0 - Real.sin(2.0 * x)) - Real.sqrt(1.0 + Real.sin(2.0 * x))) <= 0.0))
  requires (Real.cos(2.0 * x) <= 0.0) || (0.0 < Real.cos(2.0 * x))
  requires ((Real.cos(2.0 * x) <= 0.0) && (Real.sqrt(1.0 + Real.sin(2.0 * x)) * Real.sqrt(1.0 + Real.sin(2.0 * x)) - (1.0 + Real.sin(2.0 * x)) == 0.0) && (Real.cos(2.0 * x) * (Real.sqrt(1.0 + Real.sin(2.0 * x)) * Real.sqrt(1.0 + Real.sin(2.0 * x)) - (1.0 + Real.sin(2.0 * x))) == 0.0)) || (!(Real.cos(2.0 * x) <= 0.0 && Real.sqrt(1.0 + Real.sin(2.0 * x)) * Real.sqrt(1.0 + Real.sin(2.0 * x)) - (1.0 + Real.sin(2.0 * x)) == 0.0))
  requires (Real.cos(2.0 * x) <= 0.0) || (0.0 < Real.cos(2.0 * x))
  requires ((Real.cos(2.0 * x) <= 0.0) && (Real.sqrt(1.0 - Real.sin(2.0 * x)) * Real.sqrt(1.0 - Real.sin(2.0 * x)) - (1.0 - Real.sin(2.0 * x)) == 0.0) && (Real.cos(2.0 * x) * (Real.sqrt(1.0 - Real.sin(2.0 * x)) * Real.sqrt(1.0 - Real.sin(2.0 * x)) - (1.0 - Real.sin(2.0 * x))) == 0.0)) || (!(Real.cos(2.0 * x) <= 0.0 && Real.sqrt(1.0 - Real.sin(2.0 * x)) * Real.sqrt(1.0 - Real.sin(2.0 * x)) - (1.0 - Real.sin(2.0 * x)) == 0.0))
  requires ((2.0 + 2.0 * Real.cos(2.0 * x) - (Real.sqrt(1.0 - Real.sin(2.0 * x)) - Real.sqrt(1.0 + Real.sin(2.0 * x))) * (Real.sqrt(1.0 - Real.sin(2.0 * x)) - Real.sqrt(1.0 + Real.sin(2.0 * x))) < 0.0) && (0.0 < (2.0 + 2.0 * Real.cos(2.0 * x) - (Real.sqrt(1.0 - Real.sin(2.0 * x)) - Real.sqrt(1.0 + Real.sin(2.0 * x))) * (Real.sqrt(1.0 - Real.sin(2.0 * x)) - Real.sqrt(1.0 + Real.sin(2.0 * x)))) * (2.0 + 2.0 * Real.cos(2.0 * x) - (Real.sqrt(1.0 - Real.sin(2.0 * x)) - Real.sqrt(1.0 + Real.sin(2.0 * x))) * (Real.sqrt(1.0 - Real.sin(2.0 * x)) - Real.sqrt(1.0 + Real.sin(2.0 * x)))))) || (0.0 <= 2.0 + 2.0 * Real.cos(2.0 * x) - (Real.sqrt(1.0 - Real.sin(2.0 * x)) - Real.sqrt(1.0 + Real.sin(2.0 * x))) * (Real.sqrt(1.0 - Real.sin(2.0 * x)) - Real.sqrt(1.0 + Real.sin(2.0 * x))))
  requires 6.0 * (Real.sqrt(1.0 + Real.sin(2.0 * x)) * Real.sqrt(1.0 + Real.sin(2.0 * x)) - (1.0 + Real.sin(2.0 * x))) + (0.0 - 2.0 * (Real.sqrt(1.0 - Real.sin(2.0 * x)) * Real.sqrt(1.0 - Real.sin(2.0 * x)) - (1.0 - Real.sin(2.0 * x)))) + (0.0 - 4.0 * (Real.cos(2.0 * x) * Real.cos(2.0 * x) + Real.sin(2.0 * x) * Real.sin(2.0 * x) - 1.0)) + (0.0 - Real.sqrt(1.0 - Real.sin(2.0 * x)) * Real.sqrt(1.0 - Real.sin(2.0 * x)) * (Real.sqrt(1.0 + Real.sin(2.0 * x)) * Real.sqrt(1.0 + Real.sin(2.0 * x)) - (1.0 + Real.sin(2.0 * x)))) + (0.0 - Real.sqrt(1.0 - Real.sin(2.0 * x)) * Real.sqrt(1.0 - Real.sin(2.0 * x)) * (Real.sqrt(1.0 - Real.sin(2.0 * x)) * Real.sqrt(1.0 - Real.sin(2.0 * x)) - (1.0 - Real.sin(2.0 * x)))) + 2.0 * ((Real.sqrt(1.0 - Real.sin(2.0 * x)) - Real.sqrt(1.0 + Real.sin(2.0 * x))) * (Real.sqrt(1.0 - Real.sin(2.0 * x)) - Real.sqrt(1.0 + Real.sin(2.0 * x))) * (Real.sqrt(1.0 + Real.sin(2.0 * x)) * Real.sqrt(1.0 + Real.sin(2.0 * x)) - (1.0 + Real.sin(2.0 * x)))) + 2.0 * ((Real.sqrt(1.0 - Real.sin(2.0 * x)) - Real.sqrt(1.0 + Real.sin(2.0 * x))) * (Real.sqrt(1.0 - Real.sin(2.0 * x)) - Real.sqrt(1.0 + Real.sin(2.0 * x))) * (Real.sqrt(1.0 - Real.sin(2.0 * x)) * Real.sqrt(1.0 - Real.sin(2.0 * x)) - (1.0 - Real.sin(2.0 * x)))) + (0.0 - 5.0 * (Real.sqrt(1.0 + Real.sin(2.0 * x)) * Real.sqrt(1.0 + Real.sin(2.0 * x)) * (Real.sqrt(1.0 + Real.sin(2.0 * x)) * Real.sqrt(1.0 + Real.sin(2.0 * x)) - (1.0 + Real.sin(2.0 * x))))) + 3.0 * (Real.sqrt(1.0 + Real.sin(2.0 * x)) * Real.sqrt(1.0 + Real.sin(2.0 * x)) * (Real.sqrt(1.0 - Real.sin(2.0 * x)) * Real.sqrt(1.0 - Real.sin(2.0 * x)) - (1.0 - Real.sin(2.0 * x)))) + (0.0 - 4.0 * (Real.cos(2.0 * x) * ((Real.sqrt(1.0 - Real.sin(2.0 * x)) - Real.sqrt(1.0 + Real.sin(2.0 * x))) * (Real.sqrt(1.0 - Real.sin(2.0 * x)) - Real.sqrt(1.0 + Real.sin(2.0 * x))) - (2.0 + 2.0 * Real.cos(2.0 * x))))) + (0.0 - ((Real.sqrt(1.0 - Real.sin(2.0 * x)) - Real.sqrt(1.0 + Real.sin(2.0 * x))) * (Real.sqrt(1.0 - Real.sin(2.0 * x)) - Real.sqrt(1.0 + Real.sin(2.0 * x))) - (2.0 + 2.0 * Real.cos(2.0 * x))) * ((Real.sqrt(1.0 - Real.sin(2.0 * x)) - Real.sqrt(1.0 + Real.sin(2.0 * x))) * (Real.sqrt(1.0 - Real.sin(2.0 * x)) - Real.sqrt(1.0 + Real.sin(2.0 * x))) - (2.0 + 2.0 * Real.cos(2.0 * x)))) + 4.0 * ((Real.sqrt(1.0 + Real.sin(2.0 * x)) * Real.sqrt(1.0 + Real.sin(2.0 * x)) - (1.0 + Real.sin(2.0 * x))) * (Real.sqrt(1.0 + Real.sin(2.0 * x)) * Real.sqrt(1.0 + Real.sin(2.0 * x)) - (1.0 + Real.sin(2.0 * x)))) == 0.0
  requires 0.0 - 10.0 * (Real.sqrt(1.0 + Real.sin(2.0 * x)) * Real.sqrt(1.0 + Real.sin(2.0 * x)) - (1.0 + Real.sin(2.0 * x))) + (0.0 - 2.0 * (Real.sqrt(1.0 - Real.sin(2.0 * x)) * Real.sqrt(1.0 - Real.sin(2.0 * x)) - (1.0 - Real.sin(2.0 * x)))) + 4.0 * (Real.cos(2.0 * x) * Real.cos(2.0 * x) + Real.sin(2.0 * x) * Real.sin(2.0 * x) - 1.0) + Real.sqrt(1.0 - Real.sin(2.0 * x)) * Real.sqrt(1.0 - Real.sin(2.0 * x)) * (Real.sqrt(1.0 + Real.sin(2.0 * x)) * Real.sqrt(1.0 + Real.sin(2.0 * x)) - (1.0 + Real.sin(2.0 * x))) + Real.sqrt(1.0 - Real.sin(2.0 * x)) * Real.sqrt(1.0 - Real.sin(2.0 * x)) * (Real.sqrt(1.0 - Real.sin(2.0 * x)) * Real.sqrt(1.0 - Real.sin(2.0 * x)) - (1.0 - Real.sin(2.0 * x))) + 5.0 * (Real.sqrt(1.0 + Real.sin(2.0 * x)) * Real.sqrt(1.0 + Real.sin(2.0 * x)) * (Real.sqrt(1.0 + Real.sin(2.0 * x)) * Real.sqrt(1.0 + Real.sin(2.0 * x)) - (1.0 + Real.sin(2.0 * x)))) + (0.0 - 3.0 * (Real.sqrt(1.0 + Real.sin(2.0 * x)) * Real.sqrt(1.0 + Real.sin(2.0 * x)) * (Real.sqrt(1.0 - Real.sin(2.0 * x)) * Real.sqrt(1.0 - Real.sin(2.0 * x)) - (1.0 - Real.sin(2.0 * x))))) + 4.0 * (Real.sqrt(1.0 + Real.sin(2.0 * x)) * Real.sqrt(1.0 - Real.sin(2.0 * x)) * (2.0 + 2.0 * Real.cos(2.0 * x) - (Real.sqrt(1.0 - Real.sin(2.0 * x)) - Real.sqrt(1.0 + Real.sin(2.0 * x))) * (Real.sqrt(1.0 - Real.sin(2.0 * x)) - Real.sqrt(1.0 + Real.sin(2.0 * x))))) + (0.0 - 4.0 * (Real.cos(2.0 * x) * (Real.sqrt(1.0 + Real.sin(2.0 * x)) * Real.sqrt(1.0 + Real.sin(2.0 * x)) - (1.0 + Real.sin(2.0 * x))))) + (0.0 - 4.0 * (Real.cos(2.0 * x) * (Real.sqrt(1.0 - Real.sin(2.0 * x)) * Real.sqrt(1.0 - Real.sin(2.0 * x)) - (1.0 - Real.sin(2.0 * x))))) + (0.0 - (2.0 + 2.0 * Real.cos(2.0 * x) - (Real.sqrt(1.0 - Real.sin(2.0 * x)) - Real.sqrt(1.0 + Real.sin(2.0 * x))) * (Real.sqrt(1.0 - Real.sin(2.0 * x)) - Real.sqrt(1.0 + Real.sin(2.0 * x)))) * (2.0 + 2.0 * Real.cos(2.0 * x) - (Real.sqrt(1.0 - Real.sin(2.0 * x)) - Real.sqrt(1.0 + Real.sin(2.0 * x))) * (Real.sqrt(1.0 - Real.sin(2.0 * x)) - Real.sqrt(1.0 + Real.sin(2.0 * x))))) + (0.0 - 4.0 * ((Real.sqrt(1.0 + Real.sin(2.0 * x)) * Real.sqrt(1.0 + Real.sin(2.0 * x)) - (1.0 + Real.sin(2.0 * x))) * (Real.sqrt(1.0 + Real.sin(2.0 * x)) * Real.sqrt(1.0 + Real.sin(2.0 * x)) - (1.0 + Real.sin(2.0 * x))))) == 0.0
  ensures   (Real.sqrt(1.0 - Real.sin(2.0 * x)) - Real.sqrt(1.0 + Real.sin(2.0 * x))) * (Real.sqrt(1.0 - Real.sin(2.0 * x)) - Real.sqrt(1.0 + Real.sin(2.0 * x))) == 2.0 + 2.0 * Real.cos(2.0 * x)
{
          assert (0.0 <= (1.0 + Real.sin((2.0 * x)))) by {  // sub-goal of `by` (Lean state) // @tac 1383-1447
            // [TACTIC: «Nlinarith[_]At___» [ Real.sin_le_one ( 2 * x ) , Real.neg_one_le_sin ( 2 * x ) ]]
            // (n)linarith certificate: Lean's product pieces and the identity it closed with (Lean execution 1383-1447 exec 247)
            cert_identity_26(x);  // cert: add_lt_of_neg_of_le
            // UNCITED-APPLIED internal ×6 [exec 247 1383-1447]: applications made inside the tactic's own automation, not stated — le_of_not_gt ×1, add_lt_of_neg_of_le ×1, lt_zero_of_zero_gt ×1, sub_nonpos_of_le ×1; machinery/glue: Linarith.lt_irrefl ×1, congrArg ×1 (cited in this block, not counted here: Real.neg_one_le_sin [Lean recorded ×1])
            // NOT APPLIED Real.sin_le_one: named here, but Lean's proof at this tactic does not apply it (applied only at other tactics of the proof)
            RealNegOneLeSin((2.0 * x));  // cite: Real.neg_one_le_sin
            NatCastOne();  // cite: Nat.cast_one [applied by the tactic, not named in it: inside its internal steps (`ring1` exec 248)]
            NatCastZero();  // cite: Nat.cast_zero [applied by the tactic, not named in it: inside its internal steps (`ring1` exec 248)]
            // UNCITED-APPLIED internal ×31 [exec 248 1383-1447]: applications made inside the tactic's own automation, not stated — machinery/glue: Mathlib.Tactic.Ring.add_pf_zero_add ×3, Mathlib.Tactic.Ring.add_congr ×2, Mathlib.Meta.NormNum.isNat_ofNat ×2, Mathlib.Tactic.Ring.add_pf_add_lt ×2 (+20 more heads, ×22) (cited in this block, not counted here: Nat.cast_one [Lean recorded ×1], Nat.cast_zero [Lean recorded ×1])
          }
          assert (0.0 <= (1.0 - Real.sin((2.0 * x)))) by {  // sub-goal of `by` (Lean state) // @tac 1511-1575
            // [TACTIC: «Nlinarith[_]At___» [ Real.sin_le_one ( 2 * x ) , Real.neg_one_le_sin ( 2 * x ) ]]
            // (n)linarith certificate: Lean's product pieces and the identity it closed with (Lean execution 1511-1575 exec 253)
            cert_identity_27(x);  // cert: add_lt_of_neg_of_le
            // UNCITED-APPLIED internal ×6 [exec 253 1511-1575]: applications made inside the tactic's own automation, not stated — le_of_not_gt ×1, add_lt_of_neg_of_le ×1, lt_zero_of_zero_gt ×1, sub_nonpos_of_le ×1; machinery/glue: Linarith.lt_irrefl ×1, congrArg ×1 (cited in this block, not counted here: Real.sin_le_one [Lean recorded ×1])
            RealSinLeOne((2.0 * x));  // cite: Real.sin_le_one
            // NOT APPLIED Real.neg_one_le_sin: named here, but Lean's proof at this tactic does not apply it (applied only at other tactics of the proof)
            NatCastOne();  // cite: Nat.cast_one [applied by the tactic, not named in it: inside its internal steps (`ring1` exec 254)]
            NatCastZero();  // cite: Nat.cast_zero [applied by the tactic, not named in it: inside its internal steps (`ring1` exec 254)]
            // UNCITED-APPLIED internal ×33 [exec 254 1511-1575]: applications made inside the tactic's own automation, not stated — machinery/glue: Mathlib.Tactic.Ring.sub_congr ×2, Mathlib.Meta.NormNum.isNat_ofNat ×2, Mathlib.Tactic.Ring.sub_pf ×2, Mathlib.Tactic.Ring.neg_add ×2 (+21 more heads, ×25) (cited in this block, not counted here: Nat.cast_one [Lean recorded ×1], Nat.cast_zero [Lean recorded ×1])
          }
          assert (0.0 <= 2.0) by {  // sub-goal of `by` (Lean state) // @tac 1620-1628
            // [TACTIC: «Norm_num[_]At___»]
          }
          RealCosSqAddSinSq((2.0 * x));  // cite: Real.cos_sq_add_sin_sq
          NatCastOne();  // cite: Nat.cast_one [applied by the tactic, not named in it: inside its internal steps (`ring1` exec 260, 270)]
          NatCastZero();  // cite: Nat.cast_zero [applied by the tactic, not named in it: inside its internal steps (`normNum` exec 261, 262, 263, 264, 265, 266 … / `ring1` exec 260, 270)]
          SqNonneg(Real.sqrt((1.0 - Real.sin((2.0 * x)))));  // cite: sq_nonneg [applied by the tactic, not named in it]
          SqNonneg((Real.sqrt((1.0 - Real.sin((2.0 * x)))) - Real.sqrt((1.0 + Real.sin((2.0 * x))))));  // cite: sq_nonneg [applied by the tactic, not named in it]
          SqNonneg(Real.sqrt((1.0 + Real.sin((2.0 * x)))));  // cite: sq_nonneg [applied by the tactic, not named in it]
          if (((((Real.sqrt((1.0 - Real.sin((2.0 * x)))) - Real.sqrt((1.0 + Real.sin((2.0 * x))))) * (Real.sqrt((1.0 - Real.sin((2.0 * x)))) - Real.sqrt((1.0 + Real.sin((2.0 * x)))))) - (2.0 + (2.0 * Real.cos((2.0 * x)))))) < (0.0)) { LeOfLt((((Real.sqrt((1.0 - Real.sin((2.0 * x)))) - Real.sqrt((1.0 + Real.sin((2.0 * x))))) * (Real.sqrt((1.0 - Real.sin((2.0 * x)))) - Real.sqrt((1.0 + Real.sin((2.0 * x)))))) - (2.0 + (2.0 * Real.cos((2.0 * x))))), 0.0); }  // cite: le_of_lt [applied by the tactic, not named in it]
          if ((((2.0 + (2.0 * Real.cos((2.0 * x)))) - ((Real.sqrt((1.0 - Real.sin((2.0 * x)))) - Real.sqrt((1.0 + Real.sin((2.0 * x))))) * (Real.sqrt((1.0 - Real.sin((2.0 * x)))) - Real.sqrt((1.0 + Real.sin((2.0 * x)))))))) < (0.0)) { LeOfLt(((2.0 + (2.0 * Real.cos((2.0 * x)))) - ((Real.sqrt((1.0 - Real.sin((2.0 * x)))) - Real.sqrt((1.0 + Real.sin((2.0 * x))))) * (Real.sqrt((1.0 - Real.sin((2.0 * x)))) - Real.sqrt((1.0 + Real.sin((2.0 * x))))))), 0.0); }  // cite: le_of_lt [applied by the tactic, not named in it]
          // NOT APPLIED 1 of the 3 named instances of Real.sq_sqrt: Lean's records at this tactic hold only 2 distinct applications of it (which named ones: not identified)
          assert (0.0 <= ((1.0 - Real.sin((2.0 * x)))));  // precondition of RealSqSqrt (Lean: Real.sq_sqrt)
          RealSqSqrt((1.0 - Real.sin((2.0 * x))));  // cite: Real.sq_sqrt
          assert (0.0 <= ((1.0 + Real.sin((2.0 * x)))));  // precondition of RealSqSqrt (Lean: Real.sq_sqrt)
          RealSqSqrt((1.0 + Real.sin((2.0 * x))));  // cite: Real.sq_sqrt
          // (n)linarith certificate: Lean's product pieces and the identity it closed with (Lean execution 1323-1674 exec 242)
          // UNCITED-APPLIED Linarith.mul_eq: certificate piece `(6 : ℝ) * (√((1 : ℝ) + sin ((2 : ℝ) * x)) ^ (2 : ℕ) - ((1 : ℝ) + sin ((2 : ℝ) * x))) = (0 : ℝ)` not stated: a numeral multiple of a fact (linear: Dafny's arithmetic scales it natively); Lean's premises: (((Real.sqrt((1.0 + Real.sin((2.0 * x)))) * Real.sqrt((1.0 + Real.sin((2.0 * x))))) - (1.0 + Real.sin((2.0 * x)))) == 0.0); (6.0 > 0.0)
          // UNCITED-APPLIED Linarith.mul_eq: certificate piece `(2 : ℝ) * -(√((1 : ℝ) - sin ((2 : ℝ) * x)) ^ (2 : ℕ) - ((1 : ℝ) - sin ((2 : ℝ) * x))) = (0 : ℝ)` not stated: a numeral multiple of a fact (linear: Dafny's arithmetic scales it natively); Lean's premises: (-(((Real.sqrt((1.0 - Real.sin((2.0 * x)))) * Real.sqrt((1.0 - Real.sin((2.0 * x))))) - (1.0 - Real.sin((2.0 * x))))) == 0.0); (2.0 > 0.0)
          // UNCITED-APPLIED Linarith.mul_eq: certificate piece `(4 : ℝ) * -(cos ((2 : ℝ) * x) ^ (2 : ℕ) + sin ((2 : ℝ) * x) ^ (2 : ℕ) - (1 : ℝ)) = (0 : ℝ)` not stated: a numeral multiple of a fact (linear: Dafny's arithmetic scales it natively); Lean's premises: (-((((Real.cos((2.0 * x)) * Real.cos((2.0 * x))) + (Real.sin((2.0 * x)) * Real.sin((2.0 * x)))) - 1.0)) == 0.0); (4.0 > 0.0)
          if (0.0 <= (Real.sqrt((1.0 - Real.sin((2.0 * x)))) * Real.sqrt((1.0 - Real.sin((2.0 * x)))))) && (((Real.sqrt((1.0 + Real.sin((2.0 * x)))) * Real.sqrt((1.0 + Real.sin((2.0 * x))))) - (1.0 + Real.sin((2.0 * x)))) == 0.0) { assert (-(((Real.sqrt((1.0 - Real.sin((2.0 * x)))) * Real.sqrt((1.0 - Real.sin((2.0 * x))))) * ((Real.sqrt((1.0 + Real.sin((2.0 * x)))) * Real.sqrt((1.0 + Real.sin((2.0 * x))))) - (1.0 + Real.sin((2.0 * x)))))) == 0.0); }  // cert: Linarith.mul_zero_eq
          SqNonneg(Real.sqrt((1.0 - Real.sin((2.0 * x))))); assert (0.0 <= (Real.sqrt((1.0 - Real.sin((2.0 * x)))) * Real.sqrt((1.0 - Real.sin((2.0 * x))))));  // cert: sq_nonneg
          if (0.0 <= (Real.sqrt((1.0 - Real.sin((2.0 * x)))) * Real.sqrt((1.0 - Real.sin((2.0 * x)))))) && (((Real.sqrt((1.0 - Real.sin((2.0 * x)))) * Real.sqrt((1.0 - Real.sin((2.0 * x))))) - (1.0 - Real.sin((2.0 * x)))) == 0.0) { assert (-(((Real.sqrt((1.0 - Real.sin((2.0 * x)))) * Real.sqrt((1.0 - Real.sin((2.0 * x))))) * ((Real.sqrt((1.0 - Real.sin((2.0 * x)))) * Real.sqrt((1.0 - Real.sin((2.0 * x))))) - (1.0 - Real.sin((2.0 * x)))))) == 0.0); }  // cert: Linarith.mul_zero_eq
          // UNCITED-APPLIED Linarith.mul_eq: certificate piece `(2 : ℝ) * -(-(√((1 : ℝ) - sin ((2 : ℝ) * x)) - √((1 : ℝ) + sin ((2 : ℝ) * x))) ^ (2 : ℕ) * (√((1 : ℝ) + sin ((2 : ℝ) * …` not stated: a numeral multiple of a fact (linear: Dafny's arithmetic scales it natively); Lean's premises: ((((Real.sqrt((1.0 - Real.sin((2.0 * x)))) - Real.sqrt((1.0 + Real.sin((2.0 * x))))) * (Real.sqrt((1.0 - Real.sin((2.0 * x)))) - Real.sqrt((1.0 + Real.sin((2.0 * x)))))) * ((Real.sqrt((1.0 + Real.sin((2.0 * x)))) * Real.sqrt((1.0 + Real.sin((2.0 * x))))) - (1.0 + Real.sin((2.0 * x))))) == 0.0); (2.0 > 0.0)
          if (0.0 <= ((Real.sqrt((1.0 - Real.sin((2.0 * x)))) - Real.sqrt((1.0 + Real.sin((2.0 * x))))) * (Real.sqrt((1.0 - Real.sin((2.0 * x)))) - Real.sqrt((1.0 + Real.sin((2.0 * x))))))) && (((Real.sqrt((1.0 + Real.sin((2.0 * x)))) * Real.sqrt((1.0 + Real.sin((2.0 * x))))) - (1.0 + Real.sin((2.0 * x)))) == 0.0) { assert (-((((Real.sqrt((1.0 - Real.sin((2.0 * x)))) - Real.sqrt((1.0 + Real.sin((2.0 * x))))) * (Real.sqrt((1.0 - Real.sin((2.0 * x)))) - Real.sqrt((1.0 + Real.sin((2.0 * x)))))) * ((Real.sqrt((1.0 + Real.sin((2.0 * x)))) * Real.sqrt((1.0 + Real.sin((2.0 * x))))) - (1.0 + Real.sin((2.0 * x)))))) == 0.0); }  // cert: Linarith.mul_zero_eq
          SqNonneg((Real.sqrt((1.0 - Real.sin((2.0 * x)))) - Real.sqrt((1.0 + Real.sin((2.0 * x)))))); assert (0.0 <= ((Real.sqrt((1.0 - Real.sin((2.0 * x)))) - Real.sqrt((1.0 + Real.sin((2.0 * x))))) * (Real.sqrt((1.0 - Real.sin((2.0 * x)))) - Real.sqrt((1.0 + Real.sin((2.0 * x)))))));  // cert: sq_nonneg
          // UNCITED-APPLIED Linarith.mul_eq: certificate piece `(2 : ℝ) * -(-(√((1 : ℝ) - sin ((2 : ℝ) * x)) - √((1 : ℝ) + sin ((2 : ℝ) * x))) ^ (2 : ℕ) * (√((1 : ℝ) - sin ((2 : ℝ) * …` not stated: a numeral multiple of a fact (linear: Dafny's arithmetic scales it natively); Lean's premises: ((((Real.sqrt((1.0 - Real.sin((2.0 * x)))) - Real.sqrt((1.0 + Real.sin((2.0 * x))))) * (Real.sqrt((1.0 - Real.sin((2.0 * x)))) - Real.sqrt((1.0 + Real.sin((2.0 * x)))))) * ((Real.sqrt((1.0 - Real.sin((2.0 * x)))) * Real.sqrt((1.0 - Real.sin((2.0 * x))))) - (1.0 - Real.sin((2.0 * x))))) == 0.0); (2.0 > 0.0)
          if (0.0 <= ((Real.sqrt((1.0 - Real.sin((2.0 * x)))) - Real.sqrt((1.0 + Real.sin((2.0 * x))))) * (Real.sqrt((1.0 - Real.sin((2.0 * x)))) - Real.sqrt((1.0 + Real.sin((2.0 * x))))))) && (((Real.sqrt((1.0 - Real.sin((2.0 * x)))) * Real.sqrt((1.0 - Real.sin((2.0 * x))))) - (1.0 - Real.sin((2.0 * x)))) == 0.0) { assert (-((((Real.sqrt((1.0 - Real.sin((2.0 * x)))) - Real.sqrt((1.0 + Real.sin((2.0 * x))))) * (Real.sqrt((1.0 - Real.sin((2.0 * x)))) - Real.sqrt((1.0 + Real.sin((2.0 * x)))))) * ((Real.sqrt((1.0 - Real.sin((2.0 * x)))) * Real.sqrt((1.0 - Real.sin((2.0 * x))))) - (1.0 - Real.sin((2.0 * x)))))) == 0.0); }  // cert: Linarith.mul_zero_eq
          // UNCITED-APPLIED Linarith.mul_eq: certificate piece `(5 : ℝ) * (-√((1 : ℝ) + sin ((2 : ℝ) * x)) ^ (2 : ℕ) * (√((1 : ℝ) + sin ((2 : ℝ) * x)) ^ (2 : ℕ) - ((1 : ℝ) + sin ((2 :…` not stated: a numeral multiple of a fact (linear: Dafny's arithmetic scales it natively); Lean's premises: (-(((Real.sqrt((1.0 + Real.sin((2.0 * x)))) * Real.sqrt((1.0 + Real.sin((2.0 * x))))) * ((Real.sqrt((1.0 + Real.sin((2.0 * x)))) * Real.sqrt((1.0 + Real.sin((2.0 * x))))) - (1.0 + Real.sin((2.0 * x)))))) == 0.0); (5.0 > 0.0)
          if (0.0 <= (Real.sqrt((1.0 + Real.sin((2.0 * x)))) * Real.sqrt((1.0 + Real.sin((2.0 * x)))))) && (((Real.sqrt((1.0 + Real.sin((2.0 * x)))) * Real.sqrt((1.0 + Real.sin((2.0 * x))))) - (1.0 + Real.sin((2.0 * x)))) == 0.0) { assert (-(((Real.sqrt((1.0 + Real.sin((2.0 * x)))) * Real.sqrt((1.0 + Real.sin((2.0 * x))))) * ((Real.sqrt((1.0 + Real.sin((2.0 * x)))) * Real.sqrt((1.0 + Real.sin((2.0 * x))))) - (1.0 + Real.sin((2.0 * x)))))) == 0.0); }  // cert: Linarith.mul_zero_eq
          SqNonneg(Real.sqrt((1.0 + Real.sin((2.0 * x))))); assert (0.0 <= (Real.sqrt((1.0 + Real.sin((2.0 * x)))) * Real.sqrt((1.0 + Real.sin((2.0 * x))))));  // cert: sq_nonneg
          // UNCITED-APPLIED Linarith.mul_eq: certificate piece `(3 : ℝ) * -(-√((1 : ℝ) + sin ((2 : ℝ) * x)) ^ (2 : ℕ) * (√((1 : ℝ) - sin ((2 : ℝ) * x)) ^ (2 : ℕ) - ((1 : ℝ) - sin ((2 …` not stated: a numeral multiple of a fact (linear: Dafny's arithmetic scales it natively); Lean's premises: (((Real.sqrt((1.0 + Real.sin((2.0 * x)))) * Real.sqrt((1.0 + Real.sin((2.0 * x))))) * ((Real.sqrt((1.0 - Real.sin((2.0 * x)))) * Real.sqrt((1.0 - Real.sin((2.0 * x))))) - (1.0 - Real.sin((2.0 * x))))) == 0.0); (3.0 > 0.0)
          if (0.0 <= (Real.sqrt((1.0 + Real.sin((2.0 * x)))) * Real.sqrt((1.0 + Real.sin((2.0 * x)))))) && (((Real.sqrt((1.0 - Real.sin((2.0 * x)))) * Real.sqrt((1.0 - Real.sin((2.0 * x))))) - (1.0 - Real.sin((2.0 * x)))) == 0.0) { assert (-(((Real.sqrt((1.0 + Real.sin((2.0 * x)))) * Real.sqrt((1.0 + Real.sin((2.0 * x))))) * ((Real.sqrt((1.0 - Real.sin((2.0 * x)))) * Real.sqrt((1.0 - Real.sin((2.0 * x))))) - (1.0 - Real.sin((2.0 * x)))))) == 0.0); }  // cert: Linarith.mul_zero_eq
          // UNCITED-APPLIED Linarith.mul_nonpos: certificate piece `(4 : ℝ) * -(cos ((2 : ℝ) * x) * ((√((1 : ℝ) - sin ((2 : ℝ) * x)) - √((1 : ℝ) + sin ((2 : ℝ) * x))) ^ (2 : ℕ) - ((2 : ℝ)…` not stated: a numeral multiple of a fact (linear: Dafny's arithmetic scales it natively); Lean's premises: (0.0 <= (Real.cos((2.0 * x)) * (((Real.sqrt((1.0 - Real.sin((2.0 * x)))) - Real.sqrt((1.0 + Real.sin((2.0 * x))))) * (Real.sqrt((1.0 - Real.sin((2.0 * x)))) - Real.sqrt((1.0 + Real.sin((2.0 * x)))))) - (2.0 + (2.0 * Real.cos((2.0 * x))))))); (4.0 > 0.0)
          if (Real.cos((2.0 * x)) <= 0.0) && ((((Real.sqrt((1.0 - Real.sin((2.0 * x)))) - Real.sqrt((1.0 + Real.sin((2.0 * x))))) * (Real.sqrt((1.0 - Real.sin((2.0 * x)))) - Real.sqrt((1.0 + Real.sin((2.0 * x)))))) - (2.0 + (2.0 * Real.cos((2.0 * x))))) <= 0.0) { cert_piece_28(x); }  // cert: mul_nonneg_of_nonpos_of_nonpos
          if ((((Real.sqrt((1.0 - Real.sin((2.0 * x)))) - Real.sqrt((1.0 + Real.sin((2.0 * x))))) * (Real.sqrt((1.0 - Real.sin((2.0 * x)))) - Real.sqrt((1.0 + Real.sin((2.0 * x)))))) - (2.0 + (2.0 * Real.cos((2.0 * x))))) < 0.0) { cert_piece_29(x); }  // cert: mul_pos_of_neg_of_neg (square of a compound term: Z3 may not carry it through the lemma binding)
          // UNCITED-APPLIED Linarith.mul_eq: certificate piece `(4 : ℝ) * ((√((1 : ℝ) + sin ((2 : ℝ) * x)) ^ (2 : ℕ) - ((1 : ℝ) + sin ((2 : ℝ) * x))) * (√((1 : ℝ) + sin ((2 : ℝ) * x))…` not stated: a numeral multiple of a fact (linear: Dafny's arithmetic scales it natively); Lean's premises: ((((Real.sqrt((1.0 + Real.sin((2.0 * x)))) * Real.sqrt((1.0 + Real.sin((2.0 * x))))) - (1.0 + Real.sin((2.0 * x)))) * ((Real.sqrt((1.0 + Real.sin((2.0 * x)))) * Real.sqrt((1.0 + Real.sin((2.0 * x))))) - (1.0 + Real.sin((2.0 * x))))) == 0.0); (4.0 > 0.0)
          if (((Real.sqrt((1.0 + Real.sin((2.0 * x)))) * Real.sqrt((1.0 + Real.sin((2.0 * x))))) - (1.0 + Real.sin((2.0 * x)))) == 0.0) { assert ((((Real.sqrt((1.0 + Real.sin((2.0 * x)))) * Real.sqrt((1.0 + Real.sin((2.0 * x))))) - (1.0 + Real.sin((2.0 * x)))) * ((Real.sqrt((1.0 + Real.sin((2.0 * x)))) * Real.sqrt((1.0 + Real.sin((2.0 * x))))) - (1.0 + Real.sin((2.0 * x))))) == 0.0); }  // cert: Linarith.zero_mul_eq
          // UNCITED-APPLIED Linarith.mul_eq: certificate piece `(10 : ℝ) * -(√((1 : ℝ) + sin ((2 : ℝ) * x)) ^ (2 : ℕ) - ((1 : ℝ) + sin ((2 : ℝ) * x))) = (0 : ℝ)` not stated: a numeral multiple of a fact (linear: Dafny's arithmetic scales it natively); Lean's premises: (-(((Real.sqrt((1.0 + Real.sin((2.0 * x)))) * Real.sqrt((1.0 + Real.sin((2.0 * x))))) - (1.0 + Real.sin((2.0 * x))))) == 0.0); (10.0 > 0.0)
          // UNCITED-APPLIED Linarith.mul_eq: certificate piece `(4 : ℝ) * (cos ((2 : ℝ) * x) ^ (2 : ℕ) + sin ((2 : ℝ) * x) ^ (2 : ℕ) - (1 : ℝ)) = (0 : ℝ)` not stated: a numeral multiple of a fact (linear: Dafny's arithmetic scales it natively); Lean's premises: ((((Real.cos((2.0 * x)) * Real.cos((2.0 * x))) + (Real.sin((2.0 * x)) * Real.sin((2.0 * x)))) - 1.0) == 0.0); (4.0 > 0.0)
          // UNCITED-APPLIED Linarith.mul_eq: certificate piece `(5 : ℝ) * -(-√((1 : ℝ) + sin ((2 : ℝ) * x)) ^ (2 : ℕ) * (√((1 : ℝ) + sin ((2 : ℝ) * x)) ^ (2 : ℕ) - ((1 : ℝ) + sin ((2 …` not stated: a numeral multiple of a fact (linear: Dafny's arithmetic scales it natively); Lean's premises: (((Real.sqrt((1.0 + Real.sin((2.0 * x)))) * Real.sqrt((1.0 + Real.sin((2.0 * x))))) * ((Real.sqrt((1.0 + Real.sin((2.0 * x)))) * Real.sqrt((1.0 + Real.sin((2.0 * x))))) - (1.0 + Real.sin((2.0 * x))))) == 0.0); (5.0 > 0.0)
          // UNCITED-APPLIED Linarith.mul_eq: certificate piece `(3 : ℝ) * (-√((1 : ℝ) + sin ((2 : ℝ) * x)) ^ (2 : ℕ) * (√((1 : ℝ) - sin ((2 : ℝ) * x)) ^ (2 : ℕ) - ((1 : ℝ) - sin ((2 :…` not stated: a numeral multiple of a fact (linear: Dafny's arithmetic scales it natively); Lean's premises: (-(((Real.sqrt((1.0 + Real.sin((2.0 * x)))) * Real.sqrt((1.0 + Real.sin((2.0 * x))))) * ((Real.sqrt((1.0 - Real.sin((2.0 * x)))) * Real.sqrt((1.0 - Real.sin((2.0 * x))))) - (1.0 - Real.sin((2.0 * x)))))) == 0.0); (3.0 > 0.0)
          // UNCITED-APPLIED Linarith.mul_nonpos: certificate piece `(4 : ℝ) * -(-(√((1 : ℝ) + sin ((2 : ℝ) * x)) * √((1 : ℝ) - sin ((2 : ℝ) * x))) * ((2 : ℝ) + (2 : ℝ) * cos ((2 : ℝ) * x)…` not stated: a numeral multiple of a fact (linear: Dafny's arithmetic scales it natively); Lean's premises: (((Real.sqrt((1.0 + Real.sin((2.0 * x)))) * Real.sqrt((1.0 - Real.sin((2.0 * x))))) * ((2.0 + (2.0 * Real.cos((2.0 * x)))) - ((Real.sqrt((1.0 - Real.sin((2.0 * x)))) - Real.sqrt((1.0 + Real.sin((2.0 * x))))) * (Real.sqrt((1.0 - Real.sin((2.0 * x)))) - Real.sqrt((1.0 + Real.sin((2.0 * x)))))))) <= 0.0); (4.0 > 0.0)
          if (0.0 <= (Real.sqrt((1.0 + Real.sin((2.0 * x)))) * Real.sqrt((1.0 - Real.sin((2.0 * x)))))) && (((2.0 + (2.0 * Real.cos((2.0 * x)))) - ((Real.sqrt((1.0 - Real.sin((2.0 * x)))) - Real.sqrt((1.0 + Real.sin((2.0 * x))))) * (Real.sqrt((1.0 - Real.sin((2.0 * x)))) - Real.sqrt((1.0 + Real.sin((2.0 * x))))))) <= 0.0) { cert_piece_30(x); }  // cert: mul_nonneg_of_nonpos_of_nonpos
          // UNCITED-APPLIED Linarith.mul_eq: certificate piece `(4 : ℝ) * -(cos ((2 : ℝ) * x) * (√((1 : ℝ) + sin ((2 : ℝ) * x)) ^ (2 : ℕ) - ((1 : ℝ) + sin ((2 : ℝ) * x)))) = (0 : ℝ)` not stated: a numeral multiple of a fact (linear: Dafny's arithmetic scales it natively); Lean's premises: (-((Real.cos((2.0 * x)) * ((Real.sqrt((1.0 + Real.sin((2.0 * x)))) * Real.sqrt((1.0 + Real.sin((2.0 * x))))) - (1.0 + Real.sin((2.0 * x)))))) == 0.0); (4.0 > 0.0)
          if (Real.cos((2.0 * x)) <= 0.0) && (((Real.sqrt((1.0 + Real.sin((2.0 * x)))) * Real.sqrt((1.0 + Real.sin((2.0 * x))))) - (1.0 + Real.sin((2.0 * x)))) == 0.0) { assert ((Real.cos((2.0 * x)) * ((Real.sqrt((1.0 + Real.sin((2.0 * x)))) * Real.sqrt((1.0 + Real.sin((2.0 * x))))) - (1.0 + Real.sin((2.0 * x))))) == 0.0); }  // cert: Linarith.mul_zero_eq
          // UNCITED-APPLIED Linarith.mul_eq: certificate piece `(4 : ℝ) * -(cos ((2 : ℝ) * x) * (√((1 : ℝ) - sin ((2 : ℝ) * x)) ^ (2 : ℕ) - ((1 : ℝ) - sin ((2 : ℝ) * x)))) = (0 : ℝ)` not stated: a numeral multiple of a fact (linear: Dafny's arithmetic scales it natively); Lean's premises: (-((Real.cos((2.0 * x)) * ((Real.sqrt((1.0 - Real.sin((2.0 * x)))) * Real.sqrt((1.0 - Real.sin((2.0 * x))))) - (1.0 - Real.sin((2.0 * x)))))) == 0.0); (4.0 > 0.0)
          if (Real.cos((2.0 * x)) <= 0.0) && (((Real.sqrt((1.0 - Real.sin((2.0 * x)))) * Real.sqrt((1.0 - Real.sin((2.0 * x))))) - (1.0 - Real.sin((2.0 * x)))) == 0.0) { assert ((Real.cos((2.0 * x)) * ((Real.sqrt((1.0 - Real.sin((2.0 * x)))) * Real.sqrt((1.0 - Real.sin((2.0 * x))))) - (1.0 - Real.sin((2.0 * x))))) == 0.0); }  // cert: Linarith.mul_zero_eq
          if (((2.0 + (2.0 * Real.cos((2.0 * x)))) - ((Real.sqrt((1.0 - Real.sin((2.0 * x)))) - Real.sqrt((1.0 + Real.sin((2.0 * x))))) * (Real.sqrt((1.0 - Real.sin((2.0 * x)))) - Real.sqrt((1.0 + Real.sin((2.0 * x))))))) < 0.0) { cert_piece_31(x); }  // cert: mul_pos_of_neg_of_neg (square of a compound term: Z3 may not carry it through the lemma binding)
          // UNCITED-APPLIED Linarith.mul_eq: certificate piece `(4 : ℝ) * -((√((1 : ℝ) + sin ((2 : ℝ) * x)) ^ (2 : ℕ) - ((1 : ℝ) + sin ((2 : ℝ) * x))) * (√((1 : ℝ) + sin ((2 : ℝ) * x)…` not stated: a numeral multiple of a fact (linear: Dafny's arithmetic scales it natively); Lean's premises: (-((((Real.sqrt((1.0 + Real.sin((2.0 * x)))) * Real.sqrt((1.0 + Real.sin((2.0 * x))))) - (1.0 + Real.sin((2.0 * x)))) * ((Real.sqrt((1.0 + Real.sin((2.0 * x)))) * Real.sqrt((1.0 + Real.sin((2.0 * x))))) - (1.0 + Real.sin((2.0 * x)))))) == 0.0); (4.0 > 0.0)
          // UNCITED-APPLIED Linarith.eq_of_eq_of_eq: certificate sum `(6 : ℝ) * (√((1 : ℝ) + sin ((2 : ℝ) * x)) ^ (2 : ℕ) - ((1 : ℝ) + sin ((2 : ℝ) * x))) + (2 : ℝ) * -(√((1 : ℝ) - sin ((2 …` not stated: not of the form S < 0 / S <= 0 (only those are lowered, to the identity S == 0)
          // UNCITED-APPLIED Linarith.eq_of_eq_of_eq: certificate sum `(6 : ℝ) * (√((1 : ℝ) + sin ((2 : ℝ) * x)) ^ (2 : ℕ) - ((1 : ℝ) + sin ((2 : ℝ) * x))) + (2 : ℝ) * -(√((1 : ℝ) - sin ((2 …` not stated: not of the form S < 0 / S <= 0 (only those are lowered, to the identity S == 0)
          // UNCITED-APPLIED Linarith.eq_of_eq_of_eq: certificate sum `(6 : ℝ) * (√((1 : ℝ) + sin ((2 : ℝ) * x)) ^ (2 : ℕ) - ((1 : ℝ) + sin ((2 : ℝ) * x))) + (2 : ℝ) * -(√((1 : ℝ) - sin ((2 …` not stated: not of the form S < 0 / S <= 0 (only those are lowered, to the identity S == 0)
          // UNCITED-APPLIED Linarith.eq_of_eq_of_eq: certificate sum `(6 : ℝ) * (√((1 : ℝ) + sin ((2 : ℝ) * x)) ^ (2 : ℕ) - ((1 : ℝ) + sin ((2 : ℝ) * x))) + (2 : ℝ) * -(√((1 : ℝ) - sin ((2 …` not stated: not of the form S < 0 / S <= 0 (only those are lowered, to the identity S == 0)
          // UNCITED-APPLIED Linarith.eq_of_eq_of_eq: certificate sum `(6 : ℝ) * (√((1 : ℝ) + sin ((2 : ℝ) * x)) ^ (2 : ℕ) - ((1 : ℝ) + sin ((2 : ℝ) * x))) + (2 : ℝ) * -(√((1 : ℝ) - sin ((2 …` not stated: not of the form S < 0 / S <= 0 (only those are lowered, to the identity S == 0)
          // UNCITED-APPLIED Linarith.eq_of_eq_of_eq: certificate sum `(6 : ℝ) * (√((1 : ℝ) + sin ((2 : ℝ) * x)) ^ (2 : ℕ) - ((1 : ℝ) + sin ((2 : ℝ) * x))) + (2 : ℝ) * -(√((1 : ℝ) - sin ((2 …` not stated: not of the form S < 0 / S <= 0 (only those are lowered, to the identity S == 0)
          // UNCITED-APPLIED Linarith.eq_of_eq_of_eq: certificate sum `(6 : ℝ) * (√((1 : ℝ) + sin ((2 : ℝ) * x)) ^ (2 : ℕ) - ((1 : ℝ) + sin ((2 : ℝ) * x))) + (2 : ℝ) * -(√((1 : ℝ) - sin ((2 …` not stated: not of the form S < 0 / S <= 0 (only those are lowered, to the identity S == 0)
          // UNCITED-APPLIED Linarith.eq_of_eq_of_eq: certificate sum `(6 : ℝ) * (√((1 : ℝ) + sin ((2 : ℝ) * x)) ^ (2 : ℕ) - ((1 : ℝ) + sin ((2 : ℝ) * x))) + (2 : ℝ) * -(√((1 : ℝ) - sin ((2 …` not stated: not of the form S < 0 / S <= 0 (only those are lowered, to the identity S == 0)
          // UNCITED-APPLIED Linarith.eq_of_eq_of_eq: certificate sum `(10 : ℝ) * -(√((1 : ℝ) + sin ((2 : ℝ) * x)) ^ (2 : ℕ) - ((1 : ℝ) + sin ((2 : ℝ) * x))) + (2 : ℝ) * -(√((1 : ℝ) - sin ((…` not stated: not of the form S < 0 / S <= 0 (only those are lowered, to the identity S == 0)
          // UNCITED-APPLIED Linarith.eq_of_eq_of_eq: certificate sum `(10 : ℝ) * -(√((1 : ℝ) + sin ((2 : ℝ) * x)) ^ (2 : ℕ) - ((1 : ℝ) + sin ((2 : ℝ) * x))) + (2 : ℝ) * -(√((1 : ℝ) - sin ((…` not stated: not of the form S < 0 / S <= 0 (only those are lowered, to the identity S == 0)
          // UNCITED-APPLIED Linarith.eq_of_eq_of_eq: certificate sum `(10 : ℝ) * -(√((1 : ℝ) + sin ((2 : ℝ) * x)) ^ (2 : ℕ) - ((1 : ℝ) + sin ((2 : ℝ) * x))) + (2 : ℝ) * -(√((1 : ℝ) - sin ((…` not stated: not of the form S < 0 / S <= 0 (only those are lowered, to the identity S == 0)
          // UNCITED-APPLIED Linarith.eq_of_eq_of_eq: certificate sum `(10 : ℝ) * -(√((1 : ℝ) + sin ((2 : ℝ) * x)) ^ (2 : ℕ) - ((1 : ℝ) + sin ((2 : ℝ) * x))) + (2 : ℝ) * -(√((1 : ℝ) - sin ((…` not stated: not of the form S < 0 / S <= 0 (only those are lowered, to the identity S == 0)
          // UNCITED-APPLIED Linarith.eq_of_eq_of_eq: certificate sum `(10 : ℝ) * -(√((1 : ℝ) + sin ((2 : ℝ) * x)) ^ (2 : ℕ) - ((1 : ℝ) + sin ((2 : ℝ) * x))) + (2 : ℝ) * -(√((1 : ℝ) - sin ((…` not stated: not of the form S < 0 / S <= 0 (only those are lowered, to the identity S == 0)
          // UNCITED-APPLIED Linarith.eq_of_eq_of_eq: certificate sum `(10 : ℝ) * -(√((1 : ℝ) + sin ((2 : ℝ) * x)) ^ (2 : ℕ) - ((1 : ℝ) + sin ((2 : ℝ) * x))) + (2 : ℝ) * -(√((1 : ℝ) - sin ((…` not stated: not of the form S < 0 / S <= 0 (only those are lowered, to the identity S == 0)
          // UNCITED-APPLIED add_lt_of_le_of_neg ×2: certificate sums not stated: partial sums (subterms of a larger recorded sum of this certificate), e.g. `(6 : ℝ) * (√((1 : ℝ) + sin ((2 : ℝ) * x)) ^ (2 : ℕ) - ((1 : ℝ) + sin ((2 : ℝ) * x))) + (2 : ℝ) * -(√((1 : ℝ) - sin ((2 …`
          // UNCITED-APPLIED Linarith.le_of_eq_of_le ×2: certificate sums not stated: partial sums (subterms of a larger recorded sum of this certificate), e.g. `(6 : ℝ) * (√((1 : ℝ) + sin ((2 : ℝ) * x)) ^ (2 : ℕ) - ((1 : ℝ) + sin ((2 : ℝ) * x))) + (2 : ℝ) * -(√((1 : ℝ) - sin ((2 …`
          // UNCITED-APPLIED Linarith.le_of_le_of_eq ×2: certificate sums not stated: partial sums (subterms of a larger recorded sum of this certificate), e.g. `(10 : ℝ) * -(√((1 : ℝ) + sin ((2 : ℝ) * x)) ^ (2 : ℕ) - ((1 : ℝ) + sin ((2 : ℝ) * x))) + (2 : ℝ) * -(√((1 : ℝ) - sin ((…`
          cert_identity_32(x);  // cert: Linarith.lt_of_lt_of_eq
          cert_identity_33(x);  // cert: Linarith.lt_of_lt_of_eq
          // UNCITED-APPLIED internal ×49 [exec 242 1323-1674]: applications made inside the tactic's own automation, not stated — neg_eq_zero ×8, neg_nonpos_of_nonneg ×6, sub_eq_zero_of_eq ×3, mul_nonneg_of_nonpos_of_nonpos ×2, sub_neg_of_lt ×2, neg_neg_of_pos ×2, mul_pos_of_neg_of_neg ×2; machinery/glue: Linarith.mul_eq ×8, Linarith.mul_zero_eq ×8, Linarith.eq_of_eq_of_eq ×2, Linarith.mul_nonpos ×2 (+4 more heads, ×4) (cited in this block, not counted here: Real.cos_sq_add_sin_sq [Lean recorded ×1], Real.sq_sqrt [Lean recorded ×2], le_of_lt [Lean recorded ×2], sq_nonneg [Lean recorded ×3])
          // UNCITED-APPLIED internal ×272 [exec 260 1323-1674]: applications made inside the tactic's own automation, not stated — machinery/glue: Mathlib.Tactic.Ring.add_mul ×8, Mathlib.Tactic.Ring.mul_add ×8, Mathlib.Tactic.Ring.mul_zero ×8, Mathlib.Tactic.Ring.add_pf_add_zero ×8 (+46 more heads, ×240) (cited in this block, not counted here: Nat.cast_one [Lean recorded ×1], Nat.cast_zero [Lean recorded ×1])
          // UNCITED-APPLIED internal ×5 [exec 261 1323-1674]: applications made inside the tactic's own automation, not stated — machinery/glue: Mathlib.Meta.NormNum.isNat_ofNat ×2, of_eq_true ×1, eq_true ×1, Mathlib.Meta.NormNum.isNat_lt_true ×1 (cited in this block, not counted here: Nat.cast_zero [Lean recorded ×1])
          // UNCITED-APPLIED internal ×5 [exec 262 1323-1674]: applications made inside the tactic's own automation, not stated — machinery/glue: Mathlib.Meta.NormNum.isNat_ofNat ×2, of_eq_true ×1, eq_true ×1, Mathlib.Meta.NormNum.isNat_lt_true ×1 (cited in this block, not counted here: Nat.cast_zero [Lean recorded ×1])
          // UNCITED-APPLIED internal ×5 [exec 263 1323-1674]: applications made inside the tactic's own automation, not stated — machinery/glue: Mathlib.Meta.NormNum.isNat_ofNat ×2, of_eq_true ×1, eq_true ×1, Mathlib.Meta.NormNum.isNat_lt_true ×1 (cited in this block, not counted here: Nat.cast_zero [Lean recorded ×1])
          // UNCITED-APPLIED internal ×5 [exec 264 1323-1674]: applications made inside the tactic's own automation, not stated — machinery/glue: Mathlib.Meta.NormNum.isNat_ofNat ×2, of_eq_true ×1, eq_true ×1, Mathlib.Meta.NormNum.isNat_lt_true ×1 (cited in this block, not counted here: Nat.cast_zero [Lean recorded ×1])
          // UNCITED-APPLIED internal ×5 [exec 265 1323-1674]: applications made inside the tactic's own automation, not stated — machinery/glue: Mathlib.Meta.NormNum.isNat_ofNat ×2, of_eq_true ×1, eq_true ×1, Mathlib.Meta.NormNum.isNat_lt_true ×1 (cited in this block, not counted here: Nat.cast_zero [Lean recorded ×1])
          // UNCITED-APPLIED internal ×5 [exec 266 1323-1674]: applications made inside the tactic's own automation, not stated — machinery/glue: Mathlib.Meta.NormNum.isNat_ofNat ×2, of_eq_true ×1, eq_true ×1, Mathlib.Meta.NormNum.isNat_lt_true ×1 (cited in this block, not counted here: Nat.cast_zero [Lean recorded ×1])
          // UNCITED-APPLIED internal ×5 [exec 267 1323-1674]: applications made inside the tactic's own automation, not stated — machinery/glue: Mathlib.Meta.NormNum.isNat_ofNat ×2, of_eq_true ×1, eq_true ×1, Mathlib.Meta.NormNum.isNat_lt_true ×1 (cited in this block, not counted here: Nat.cast_zero [Lean recorded ×1])
          // UNCITED-APPLIED internal ×5 [exec 268 1323-1674]: applications made inside the tactic's own automation, not stated — machinery/glue: Mathlib.Meta.NormNum.isNat_ofNat ×2, of_eq_true ×1, eq_true ×1, Mathlib.Meta.NormNum.isNat_lt_true ×1 (cited in this block, not counted here: Nat.cast_zero [Lean recorded ×1])
          // UNCITED-APPLIED internal ×5 [exec 269 1323-1674]: applications made inside the tactic's own automation, not stated — machinery/glue: Mathlib.Meta.NormNum.isNat_ofNat ×2, of_eq_true ×1, eq_true ×1, Mathlib.Meta.NormNum.isNat_lt_true ×1 (cited in this block, not counted here: Nat.cast_zero [Lean recorded ×1])
          // UNCITED-APPLIED internal ×279 [exec 270 1323-1674]: applications made inside the tactic's own automation, not stated — machinery/glue: Mathlib.Tactic.Ring.mul_congr ×8, Mathlib.Tactic.Ring.add_mul ×8, Mathlib.Tactic.Ring.mul_add ×8, Mathlib.Tactic.Ring.mul_zero ×8 (+46 more heads, ×247) (cited in this block, not counted here: Nat.cast_one [Lean recorded ×1], Nat.cast_zero [Lean recorded ×1])
          // UNCITED-APPLIED internal ×5 [exec 271 1323-1674]: applications made inside the tactic's own automation, not stated — machinery/glue: Mathlib.Meta.NormNum.isNat_ofNat ×2, of_eq_true ×1, eq_true ×1, Mathlib.Meta.NormNum.isNat_lt_true ×1 (cited in this block, not counted here: Nat.cast_zero [Lean recorded ×1])
          // UNCITED-APPLIED internal ×5 [exec 272 1323-1674]: applications made inside the tactic's own automation, not stated — machinery/glue: Mathlib.Meta.NormNum.isNat_ofNat ×2, of_eq_true ×1, eq_true ×1, Mathlib.Meta.NormNum.isNat_lt_true ×1 (cited in this block, not counted here: Nat.cast_zero [Lean recorded ×1])
          // UNCITED-APPLIED internal ×5 [exec 273 1323-1674]: applications made inside the tactic's own automation, not stated — machinery/glue: Mathlib.Meta.NormNum.isNat_ofNat ×2, of_eq_true ×1, eq_true ×1, Mathlib.Meta.NormNum.isNat_lt_true ×1 (cited in this block, not counted here: Nat.cast_zero [Lean recorded ×1])
          // UNCITED-APPLIED internal ×5 [exec 274 1323-1674]: applications made inside the tactic's own automation, not stated — machinery/glue: Mathlib.Meta.NormNum.isNat_ofNat ×2, of_eq_true ×1, eq_true ×1, Mathlib.Meta.NormNum.isNat_lt_true ×1 (cited in this block, not counted here: Nat.cast_zero [Lean recorded ×1])
          // UNCITED-APPLIED internal ×5 [exec 275 1323-1674]: applications made inside the tactic's own automation, not stated — machinery/glue: Mathlib.Meta.NormNum.isNat_ofNat ×2, of_eq_true ×1, eq_true ×1, Mathlib.Meta.NormNum.isNat_lt_true ×1 (cited in this block, not counted here: Nat.cast_zero [Lean recorded ×1])
          // UNCITED-APPLIED internal ×5 [exec 276 1323-1674]: applications made inside the tactic's own automation, not stated — machinery/glue: Mathlib.Meta.NormNum.isNat_ofNat ×2, of_eq_true ×1, eq_true ×1, Mathlib.Meta.NormNum.isNat_lt_true ×1 (cited in this block, not counted here: Nat.cast_zero [Lean recorded ×1])
          // UNCITED-APPLIED internal ×5 [exec 277 1323-1674]: applications made inside the tactic's own automation, not stated — machinery/glue: Mathlib.Meta.NormNum.isNat_ofNat ×2, of_eq_true ×1, eq_true ×1, Mathlib.Meta.NormNum.isNat_lt_true ×1 (cited in this block, not counted here: Nat.cast_zero [Lean recorded ×1])
          // UNCITED-APPLIED internal ×5 [exec 278 1323-1674]: applications made inside the tactic's own automation, not stated — machinery/glue: Mathlib.Meta.NormNum.isNat_ofNat ×2, of_eq_true ×1, eq_true ×1, Mathlib.Meta.NormNum.isNat_lt_true ×1 (cited in this block, not counted here: Nat.cast_zero [Lean recorded ×1])
          // UNCITED-APPLIED internal ×5 [exec 279 1323-1674]: applications made inside the tactic's own automation, not stated — machinery/glue: Mathlib.Meta.NormNum.isNat_ofNat ×2, of_eq_true ×1, eq_true ×1, Mathlib.Meta.NormNum.isNat_lt_true ×1 (cited in this block, not counted here: Nat.cast_zero [Lean recorded ×1])
}

